--select * from GRIDCOLUMNAXUSUARIO;

-- DELETE FROM GRIDCOLUMNAXUSUARIO;

Insert into GRIDCOLUMNAXUSUARIO
   (IDUSUARIO, IDGRIDCOLUMNA, WIDTH, HIDDEN, POSITION, 
    ORDENADO)
 Values
   (1, 90, '25px', 0, 1, 
    'N');
Insert into GRIDCOLUMNAXUSUARIO
   (IDUSUARIO, IDGRIDCOLUMNA, WIDTH, HIDDEN, POSITION, 
    ORDENADO)
 Values
   (1, 100, '30px', 1, 2, 
    'N');
Insert into GRIDCOLUMNAXUSUARIO
   (IDUSUARIO, IDGRIDCOLUMNA, WIDTH, HIDDEN, POSITION, 
    ORDENADO)
 Values
   (1, 101, '30px', 0, 3, 
    'N');
Insert into GRIDCOLUMNAXUSUARIO
   (IDUSUARIO, IDGRIDCOLUMNA, WIDTH, HIDDEN, POSITION, 
    ORDENADO)
 Values
   (1, 104, '70px', 0, 4, 
    'N');
Insert into GRIDCOLUMNAXUSUARIO
   (IDUSUARIO, IDGRIDCOLUMNA, WIDTH, HIDDEN, POSITION, 
    ORDENADO)
 Values
   (1, 110, '150px', 0, 5, 
    'N');
Insert into GRIDCOLUMNAXUSUARIO
   (IDUSUARIO, IDGRIDCOLUMNA, WIDTH, HIDDEN, POSITION, 
    ORDENADO)
 Values
   (1, 120, '220px', 0, 6, 
    'N');
Insert into GRIDCOLUMNAXUSUARIO
   (IDUSUARIO, IDGRIDCOLUMNA, WIDTH, HIDDEN, POSITION, 
    ORDENADO)
 Values
   (1, 121, '150px', 0, 7, 
    'N');
Insert into GRIDCOLUMNAXUSUARIO
   (IDUSUARIO, IDGRIDCOLUMNA, WIDTH, HIDDEN, POSITION, 
    ORDENADO)
 Values
   (1, 122, '100px', 0, 8, 
    'N');
Insert into GRIDCOLUMNAXUSUARIO
   (IDUSUARIO, IDGRIDCOLUMNA, WIDTH, HIDDEN, POSITION, 
    ORDENADO)
 Values
   (1, 123, '150px', 0, 9, 
    'N');
Insert into GRIDCOLUMNAXUSUARIO
   (IDUSUARIO, IDGRIDCOLUMNA, WIDTH, HIDDEN, POSITION, 
    ORDENADO)
 Values
   (1, 124, '200px', 0, 10, 
    'N');
Insert into GRIDCOLUMNAXUSUARIO
   (IDUSUARIO, IDGRIDCOLUMNA, WIDTH, HIDDEN, POSITION, 
    ORDENADO)
 Values
   (1, 125, '150px', 0, 11, 
    'N');
Insert into GRIDCOLUMNAXUSUARIO
   (IDUSUARIO, IDGRIDCOLUMNA, WIDTH, HIDDEN, POSITION, 
    ORDENADO)
 Values
   (1, 126, '150px', 0, 12, 
    'N');
Insert into GRIDCOLUMNAXUSUARIO
   (IDUSUARIO, IDGRIDCOLUMNA, WIDTH, HIDDEN, POSITION, 
    ORDENADO)
 Values
   (1, 151, '150px', 0, 13, 
    'N');
Insert into GRIDCOLUMNAXUSUARIO
   (IDUSUARIO, IDGRIDCOLUMNA, WIDTH, HIDDEN, POSITION, 
    ORDENADO)
 Values
   (1, 161, '220px', 0, 14, 
    'N');

