--SET IDENTITY_INSERT PARAMETRO ON;
--select * from PARAMETRO;
--delete from PARAMETRO;

Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (531, 'CLASE_LEGAJO', 'E', 'EXISTENCIAS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (530, 'CLASE_LEGAJO', 'BP', 'BIENES PATRIMONIALES', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (529, 'CLASE_AB_LEGAJO', 'BP', 'BIENES PATRIMONIALES', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (528, 'CLASE_AB_LEGAJO', 'E', 'EXISTENCIAS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (527, 'CLASE_DB_LEGAJO', 'E', 'EXISTENCIAS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (526, 'CLASE_DB_LEGAJO', 'BP', 'BIENES PATRIMONIALES', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (525, 'TIPO_DOCUMENTO_INSTITUCIONAL', '518', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (524, 'TIPO_DOCUMENTO_INSTITUCIONAL', '517', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (523, 'TIPO_DOCUMENTO_INSTITUCIONAL', '516', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (522, 'TIPO_DOCUMENTO_INSTITUCIONAL', '396', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (521, 'TIPO_DOCUMENTO_INSTITUCIONAL', '442', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (520, 'WSDL_PROXY_OSITRAN', 'https://serviciosdigitales.ositran.gob.pe:8443/wsiotramitempv/TramiteMPV?wsdl', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (519, 'WSDL_SEDE_DIGITAL', 'https://ositran.administracionelectronica.net/PortalEmpleado/Services?wsdl', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (518, 'MENSAJE_TRAMITE', 'MT_1', 'El documento ya se encuentra registrado con NT: %1 y Carpeta: %2', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (517, 'FECHA_ENV_UNIFICADO_DESPACHO', '20210401', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (516, 'MENSAJE_FISICO_CORREO_MPV_CLIENTE', 'MC_7', 'El documento se encuentra con coodinación.', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (515, 'IMAGEN_CANAL_DOCUMENTO', 'P', './images/despacho.png', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (514, 'IMAGEN_CANAL_DOCUMENTO', 'M', './images/recepcion.png', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (513, 'IMAGEN_CANAL_DOCUMENTO', 'C', './images/EmailRead16.gif', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (512, 'IMAGEN_CANAL_DOCUMENTO', 'F', './images/fisico.png', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (511, 'IMAGEN_CANAL_DOCUMENTO', 'V', './images/mp-destinatario.png', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (510, 'IMAGEN_CANAL_DOCUMENTO', 'Y', './images/recepcionmpv.png', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (509, 'IMAGEN_CANAL_DOCUMENTO', 'X', './images/recepcionmpv.png', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (508, 'IMAGEN_CANAL_DOCUMENTO', 'U', './images/leaf.gif', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (507, 'DESCRIPCION_CANAL_DOCUMENTO', 'U', 'Fisico', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (506, 'DESCRIPCION_CANAL_DOCUMENTO', 'Y', 'SEDE', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (505, 'DESCRIPCION_CANAL_DOCUMENTO', 'X', 'SEDE', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (504, 'DESCRIPCION_CANAL_DOCUMENTO', 'V', 'MPV', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (503, 'DESCRIPCION_CANAL_DOCUMENTO', 'F', 'Fisico', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (502, 'DESCRIPCION_CANAL_DOCUMENTO', 'C', 'Correo', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (501, 'DESCRIPCION_CANAL_DOCUMENTO', 'M', 'Casilla', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (500, 'DESCRIPCION_CANAL_DOCUMENTO', 'P', 'PIDE', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (499, 'RUTA_FIRMA_CODIGO_BARRA', '/FILES_FIRMA_BARRA/', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (498, 'MENSAJE_CASILLA_CLIENTE', 'MC_10', 'El documento fue rechazado satisfactoriamente', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (497, 'MENSAJE_CASILLA_CLIENTE', 'MC_9', 'La observación se realizó satisfactoriamente.', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (496, 'MENSAJE_FISICO_CORREO_MPV_CLIENTE', 'MC_6', 'La observación se realizó satisfactoriamente.', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (495, 'MENSAJE_FISICO_CORREO_MPV_CLIENTE', 'MC_5', 'Se asignó la constancia satisfactoriamente.', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (494, 'MENSAJE_FISICO_CORREO_MPV_CLIENTE', 'MC_4', 'La recepción se realizó satisfactoriamente.', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (493, 'MENSAJE_FISICO_CORREO_MPV_CLIENTE', 'MC_3', 'El documento se envió satisfactoriamente.', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (492, 'MENSAJE_FISICO_CORREO_MPV_CLIENTE', 'MC_2', 'Se produjo un error inesperado. Vuelva a intentar.', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (491, 'MENSAJE_FISICO_CORREO_MPV_CLIENTE', 'MC_1', 'El cambio de estado no puede ser procesado. Verificar', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (490, 'MENSAJE_CASILLA_CLIENTE', 'MC_8', 'El documento se envio satisfactoriamente.', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (489, 'MENSAJE_PIDE_CLIENTE', 'MC_10', 'No se pudo procesar su solicitud. Vuelva a intentarlo.', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (488, 'MENSAJE_PIDE_CLIENTE', 'MC_9', 'El Cargo debe ser firmado', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (487, 'MENSAJE_CASILLA_CLIENTE', 'MC_4', 'El Cargo debe ser Firmado', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (486, 'MENSAJE_CASILLA_CLIENTE', 'MC_7', 'La Recepción se realizó satisfactoriamente. Debe realizar el envio del Cargo por correo electrónico', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (485, 'MENSAJE_CASILLA_CLIENTE', 'MC_6', 'No se pudo procesar su solicitud. Vuelva a intentarlo.', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (484, 'MENSAJE_CASILLA_CLIENTE', 'MC_5', 'La Recepción se realizó satisfactoriamente', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (482, 'MENSAJE_CASILLA_CLIENTE', 'MC_3', 'El cambio de estado no puede ser procesado', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (481, 'MENSAJE_CASILLA_CLIENTE', 'MC_2', 'No se pudo establecer comunicacion con la Mesa de Parte Virtual. Vuelva a Intentar.', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (480, 'MENSAJE_CASILLA_CLIENTE', 'MC_1', 'El usuario no tiene Alta.', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (479, 'MENSAJE_PIDE_CLIENTE', 'MC_8', 'La Entidad no tiene PIDE.', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (478, 'MENSAJE_PIDE_CLIENTE', 'MC_7', 'No se pudo establecer comunicacion con la PIDE. Vuelva a Intentar.', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (477, 'ESTADOS_PIDE', 'Z', 'Rechazado', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (476, 'ESTADO_CONSULTA_TRAMITE', 'A', 'PRESENTADO', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (475, 'ESTADO_CONSULTA_TRAMITE', 'T', 'ATENDIDO', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (474, 'ESTADO_CONSULTA_TRAMITE', 'S', 'RECIBIDO CON OBSERVACIONES', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (473, 'ESTADO_CONSULTA_TRAMITE', 'O', 'OBSERVADO', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (472, 'ESTADO_CONSULTA_TRAMITE', 'R', 'RECIBIDO', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (471, 'ESTADO_CONSULTA_TRAMITE', 'P', 'EN PROCESO', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (470, 'ENVIO_SEDE_DIGITAL', '1', 'MPV', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (469, 'ENVIO_SEDE_DIGITAL', '0', 'MPV', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (468, 'ENVIO_SEDE_DIGITAL', '3', 'EDEE', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (467, 'USUARIOS_JEFATURAS_GA', '933', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (466, 'USUARIOS_JEFATURAS_GA', '534', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (465, 'DIAS_PENDIENTES_UNIFICACION_DESPACHO', '350', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (464, 'ESTADOS_PIDE', 'X', 'Todos', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (463, 'TIPO_OFICIO_CIRCULAR', '2', 'Varios Archivos Principales', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (462, 'TIPO_OFICIO_CIRCULAR', '1', 'Un Solo Archivo Principal', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (461, 'MENSAJE_PIDE_CLIENTE', 'MC_6', 'El cambio de estado no puede ser procesado. Verificar', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (460, 'FECHA_PUB_UNIFICACION_DESPACHO', '202012052330', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (459, 'FLAG_SELLO_TIEMPO', '1', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (458, 'PERMISO_CARGO', '1035', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (457, 'PERMISO_CARGO', '510', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (456, 'PERMISO_CARGO', '1192', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (455, 'PERMISO_CARGO', '1161', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (454, 'PERMISO_CARGO', '1237', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (453, 'FLAG_VALIDAR_DOCUMENTOS_ENVIO', '1', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (452, 'FLAG_VALIDAR_DOCUMENTOS_ENVIO_PORTAL', '1', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (451, 'FECHA_PUB_PORTAL_DOCUMENTOS', '20200625', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (450, 'NUM_MAX_CARACTERES_ARCHIVO', '85', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (449, 'IP_INTERNO_OSITRAN', '100.134', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (448, 'CLAVE_OSITRAN', 'zooU2-2000_xx_yyBZRaMMM21025', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (447, 'USUARIO_OSITRAN', 'OsitranPeru', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (446, 'MENSAJE_DESPACHO_NOTIFICACION', '<br>Estimado (a)<br><br>El OSITRAN le ha enviado el siguiente documento: %1%.<br><br>', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (445, 'MENSAJE_DESPACHO_RESPUESTA', '<br>Estimado (a)<br><br>El presente documento %1% es respuesta del documento %2%. <br><br>', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (444, 'MENSAJE_RECEPCION_OBSERVADO', '<br>Estimado (a)<br><br>El documento %1% ha sido recibido con Observaciones en la Mesa de Partes Virtual del OSITRAN, las cuales se detallan a continuación: %2%. <br><br>', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (443, 'MENSAJE_RECEPCION_CORRECTA', '<br>Estimado (a)<br><br>El documento, %1% ha sido recepcionado por la Mesa de Partes Virtual del OSITRAN. La admisión se realizará en el horario de atención del OSITRAN. <br><br>', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (442, 'CLAVE_MPV', 'zgYjE2azPBMBSk6a', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (441, 'USUARIO_MPV', 'Indenova', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (434, 'RESOLUCION_MULTA_ARTICULO', '5', '176° 2', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (433, 'NUMERO_NIVELES_ARBOL', '5', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (432, 'DIMENSION_CODIGO_BARRA_HEIGHT', '50', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (431, 'DIMENSION_CODIGO_BARRA_WIDTH', '150', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (430, 'TIEMPO_SESSION_COMPONENTE_FIRMA', '80', 'Los documentos estan siendo firmados/visados por otro usuario. Espere % segundos y vuelva a procesar.', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (429, 'TRIBUNAL_FISCAL_CASACION_INSTANCIA', '52', 'DECISION FINAL', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (428, 'TRIBUNAL_FISCAL_CASACION_INSTANCIA', '51', 'AUDIENCIA DE VISTA DE LA CAUSA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (427, 'TRIBUNAL_FISCAL_CASACION_INSTANCIA', '50', 'CALIFICACION DE PROCEDENCIA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, ESTADO)
 Values
   (426, 'TRIBUNAL_FISCAL_CASACION_INSTANCIA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (425, 'TRIBUNAL_FISCAL_SEGUNDA_INSTANCIA', '33', 'INTERPOSICION DEL RECURSO DE CASACION', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (424, 'TRIBUNAL_FISCAL_SEGUNDA_INSTANCIA', '32', 'SENTENCIA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (423, 'TRIBUNAL_FISCAL_SEGUNDA_INSTANCIA', '31', 'AUDIENCIA DE VISTA DE LA CAUSA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (422, 'TRIBUNAL_FISCAL_SEGUNDA_INSTANCIA', '30', 'TRASLADO DEL RECURSO DE APELACION', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, ESTADO)
 Values
   (421, 'TRIBUNAL_FISCAL_SEGUNDA_INSTANCIA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (420, 'TRIBUNAL_FISCAL_PRIMERA_INSTANCIA', '6', 'INTERPOSICION DEL RECURSO DE APELACION CONTRA LA SENTENCIA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (419, 'TRIBUNAL_FISCAL_PRIMERA_INSTANCIA', '5', 'SENTENCIA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (418, 'TRIBUNAL_FISCAL_PRIMERA_INSTANCIA', '4', 'AUDIENCIA DE INFORME ORAL', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (417, 'TRIBUNAL_FISCAL_PRIMERA_INSTANCIA', '3', 'SANEAMIENTO PROCESAL', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (416, 'TRIBUNAL_FISCAL_PRIMERA_INSTANCIA', '2', 'POSTULATORIA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (415, 'TRIBUNAL_FISCAL_PRIMERA_INSTANCIA', '1', 'CALIFICACION', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, ESTADO)
 Values
   (414, 'TRIBUNAL_FISCAL_PRIMERA_INSTANCIA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (413, 'TRIBUNAL_FISCAL_INSTANCIA', '3', 'CASACION', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (412, 'TRIBUNAL_FISCAL_INSTANCIA', '2', 'SEGUNDA INSTANCIA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (411, 'TRIBUNAL_FISCAL_INSTANCIA', '1', 'PRIMERA INSTANCIA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, ESTADO)
 Values
   (410, 'TRIBUNAL_FISCAL_INSTANCIA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (409, 'APELACION_FISCAL_SALA', '8', 'SALA 08', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (408, 'APELACION_FISCAL_SALA', '7', 'SALA 07', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (407, 'APELACION_FISCAL_SALA', '6', 'SALA 06', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (406, 'APELACION_FISCAL_SALA', '5', 'SALA 05', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (405, 'APELACION_FISCAL_SALA', '4', 'SALA 04', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (404, 'APELACION_FISCAL_SALA', '3', 'SALA 03', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (403, 'APELACION_FISCAL_SALA', '2', 'SALA 02', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (402, 'APELACION_FISCAL_SALA', '1', 'SALA 01', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, ESTADO)
 Values
   (401, 'APELACION_FISCAL_SALA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (400, 'APELACION_FISCAL_SITUACION', '3', 'DECISION DEL TRIBUNAL FISCAL', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (399, 'APELACION_FISCAL_SITUACION', '2', 'AUDIENCIA DE INFORME ORAL', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (398, 'APELACION_FISCAL_SITUACION', '1', 'ASIGNACION DEL CASO A UNA SALA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, ESTADO)
 Values
   (397, 'APELACION_FISCAL_SITUACION', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (396, 'TRIBUNAL_FISCAL_SITUACION', '7', 'CASACION', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (395, 'TRIBUNAL_FISCAL_SITUACION', '6', 'REVISORIA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (394, 'TRIBUNAL_FISCAL_SITUACION', '5', 'IMPUGNACION', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (393, 'TRIBUNAL_FISCAL_SITUACION', '4', 'CONCILIACION', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (392, 'TRIBUNAL_FISCAL_SITUACION', '3', 'SANEAMIENTO', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (391, 'TRIBUNAL_FISCAL_SITUACION', '2', 'CALIFICADA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (390, 'TRIBUNAL_FISCAL_SITUACION', '1', 'EN CALIFICACION', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, ESTADO)
 Values
   (389, 'TRIBUNAL_FISCAL_SITUACION', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (388, 'TRIBUNAL_FISCAL_TERCERO', '2', 'CONTRIBUYENTE', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (387, 'TRIBUNAL_FISCAL_TERCERO', '1', 'OSITRAN', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, ESTADO)
 Values
   (386, 'TRIBUNAL_FISCAL_TERCERO', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (385, 'EXPEDIENTE_VINCULADO_FISCALIZACION', '8', '8', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (384, 'EXPEDIENTE_VINCULADO_FISCALIZACION', '7', '7', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (383, 'EXPEDIENTE_VINCULADO_FISCALIZACION', '6', '6', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (382, 'EXPEDIENTE_VINCULADO_FISCALIZACION', '5', '5', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (381, 'EXPEDIENTE_FISCALIZACION', '4', '4', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (380, 'GERENTE_GSF', '236', '236', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (379, 'RESOLUCION_MULTA_TIPO_DOCUMENTO', '15', 'OFICIO', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (378, 'TIPO_DOCUMENTO_REQUERIMIENTO', '486', '486', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (377, 'TIPO_DOCUMENTO_RESOLUCION_MULTA', '453', 'RESOLUCION MULTA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (376, 'RESOLUCION_MULTA_ARTICULO', '1', '178° 1', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (375, 'RESOLUCION_MULTA_ARTICULO', '2', '177° 5', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (374, 'RESOLUCION_MULTA_ARTICULO', '3', '177° 1', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (373, 'RESOLUCION_MULTA_ARTICULO', '4', '176° 1', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (372, 'TIPO_DOCUMENTO_RESOLUCION_DETERMINACION', '471', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (371, 'RESOLUCION_MULTA_MONTO_MINIMO', '5', '5% UIT', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (370, 'RESOLUCION_MULTA_MONTO_MINIMO', '0', 'SIN MONTO', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (369, 'RESOLUCION_DETERMINACION_TASA', '1', '1%', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (368, 'RESOLUCION_DETERMINACION_ARTICULO', '10', '76', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (367, 'TIPO_DOCUMENTO_RESULTADO', '487', '487', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (366, 'RESOLUCION_TRIBUTO', '1', 'APORTE POR REGULACIÓN', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (365, 'RESOLUCION_MULTA_TASA', '50', '50%', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (364, 'PROCEDIMIENTO_LEGAJO', 'PSA', 'Procedimiento de Selección Abreviado', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (363, 'PROCEDIMIENTO_LEGAJO', 'PSO', 'Procedimiento de Selección Ordinario', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (361, 'TIPO_LEGAJO', '3', 'EXPEDIENTE DE CONTRATACION MENORES', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (360, 'TIPO_LEGAJO', '2', 'EXPEDIENTE DE CONTRATACION', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (359, 'TIPO_LEGAJO', '1', 'EXPEDIENTE DE PAGOS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (358, 'PERMISO_CARGO', '121', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (357, 'RESPUESTA_MIGRACIONES', '0001', 'Sin error, no se encontraron datos del Carnet de Extranjería o el Carnet de Extranjería no está vigente', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (356, 'RESPUESTA_MIGRACIONES', '0002', 'Con error, sin conexión', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (355, 'RESPUESTA_MIGRACIONES', '0003', 'Con error, transacción no exitosa', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (354, 'RESPUESTA_MIGRACIONES', '0004', 'Con error, no está permitido el uso de valores nulos o vacíos en la consulta', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (353, 'RESPUESTA_MIGRACIONES', '0005', 'Con error, no está permitido realizar la consulta con los valores de IP, MAC ADDRES y CODIGO DE INSTITUCION ingresados', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (352, 'METODO_LEGAJO', 'RG', 'Régimen General', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (351, 'METODO_LEGAJO', 'AM', 'Acuerdo de Marco', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (350, 'METODO_LEGAJO', 'RE', 'Régimen Especial', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (349, 'PROCEDIMIENTO_LEGAJO', 'CD', 'Contratación Directa', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (348, 'PROCEDIMIENTO_LEGAJO', 'SIE', 'Subasta Inversa Electrónica', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (347, 'PROCEDIMIENTO_LEGAJO', 'CDP', 'Comparación de Precios', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (346, 'PROCEDIMIENTO_LEGAJO', 'AS', 'Adjudicación Simplificada', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (345, 'PROCEDIMIENTO_LEGAJO', 'CP', 'Concurso Público', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (344, 'PROCEDIMIENTO_LEGAJO', 'LP', 'Licitación Pública', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (343, 'COD_MIGRACIONES', 'PCM', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (342, 'IP_MIGRACIONES', '200.48.76.68', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (341, 'MAC_MIGRACIONES', '54:52:00:0A:85:FE', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (340, 'RESPUESTA_MIGRACIONES', '0007', 'Con error, la información del documento consultado no puede ser mostrada porque pertenece a un menor de edad', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (339, 'RESPUESTA_MIGRACIONES', '0006', 'Con error, el tipo de documento ingresado no es el correcto', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (337, 'PERMISO_CARGO', '1012', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (336, 'ESTADOS_PIDE', 'S', 'Subsanado', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (335, 'ESTADOS_PIDE', 'E', 'Enviado', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (334, 'PERMISO_CARGO', '1069', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (333, 'PERMISO_CARGO', '1002', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (332, 'PERMISO_CARGO', '1011', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (331, 'PERMISO_CARGO', '1004', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (330, 'PERMISO_CARGO', '970', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (329, 'PERMISO_CARGO', '193', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (328, 'PERMISO_CARGO', '1056', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (327, 'PERMISO_CARGO', '1082', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (326, 'prefijonrolegajoproduccion', '00000', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (325, 'AREAS_ACCESO_GENERAL', '18', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (324, 'AREAS_ACCESO_GENERAL', '13', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (323, 'UNIDAD_GSF', '58', 'Gerente de Supervisión y Fiscalización', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (322, 'TIPO_DOCUMENTO_RESULTADO_TRIBUTARIO', '464', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (318, 'USUARIO_MP_DOC_PCM', '193', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (317, 'USUARIO_MP_DOC_CR', '193', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (316, 'USUARIO_MP_DOC_MTC', '266', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (315, 'USUARIO_MP_DOC_PCM', '768', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (314, 'USUARIO_MP_DOC_CR', '768', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (313, 'CLIENTE_MP_DOC_MTC', '37465', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (312, 'CLIENTE_MP_DOC_CR', '37535', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (311, 'CLIENTE_MP_DOC_PCM', '37498', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (310, 'USUARIO_MP_DOC_MTC', '193', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (301, 'MAIL_FILEPATH_DOCUMENTO_PARTICULAR_PCM', 'particularpcm.txt', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (300, 'MAIL_FILEPATH_DOCUMENTO_PARTICULAR_CR', 'particularcr.txt', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (299, 'MAIL_FILEPATH_DOCUMENTO_PARTICULAR_MTC', 'particularmtc.txt', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (298, 'TIPO_DOCUMENTO_REQUERIMIENTO_TRIBUTARIO', '463', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (297, 'KEY_SGD', '10028125110745395283635306554236241928', '10028125110745395283635306554236241928', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (293, 'MENSAJE_PIDE_CLIENTE', 'MC_5', 'No se pudo realizar el envío del documento', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (292, 'MENSAJE_PIDE_CLIENTE', 'MC_4', 'No se pudo generar el CUO', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (291, 'URL_ANEXOS_PIDE', 'PIDE', 'https://servicios.ositran.gob.pe:8443/SGDEntidades', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (290, 'RAZON_SOCIAL_OSITRAN', '20420248645', 'ORGANISMO SUPERVISOR DE LA INVERSION EN INFRAESTRUCTURA DE TRANSPORTE DE USO PUBLICO - OSITRAN', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (289, 'MENSAJE_PIDE_CLIENTE', 'MC_3', 'No se pudo realizar el envio del documento. Vuelva a intentarlo', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (288, 'MENSAJE_PIDE_CLIENTE', 'MC_2', 'Su información se registro satisfactoriamente, pero no se pudo obtener la confirmación de recepción del cargo por la entidad emisora', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (287, 'MENSAJE_PIDE_CLIENTE', 'MC_1', 'Se recepcionó el documento con éxito', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (286, 'RUC_OSITRAN', '20420248645', '20420248645', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (285, 'ESTADOS_RECEPCION', 'O', 'Observado', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (284, 'ESTADOS_RECEPCION', 'R', 'Recepcionado', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (283, 'ESTADOS_PIDE', 'O', 'Observado', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (282, 'ESTADOS_PIDE', 'R', 'Recepcionado', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (281, 'ESTADOS_PIDE', 'P', 'Pendiente', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (280, 'PROYECTO', '1', 'Final', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (279, 'PROYECTO', '2', 'Proyecto', '0');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (278, 'TIPOS_DE_ADJUNTOS_MP', '023', 'FOTOCHECKS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (277, 'TIPOS_DE_ADJUNTOS_MP', '022', 'PROPUESTA ECONOMICA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (276, 'TIPOS_DE_ADJUNTOS_MP', '021', 'PROPUESTA TECNICA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (275, 'TIPOS_DE_ADJUNTOS_MP', '020', 'PAQUETES', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (274, 'TIPOS_DE_ADJUNTOS_MP', '019', 'MEMORIAS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (273, 'TIPOS_DE_ADJUNTOS_MP', '018', 'CUADERNOS DE OBRA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (272, 'TIPOS_DE_ADJUNTOS_MP', '017', 'SOBRE', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (271, 'TIPOS_DE_ADJUNTOS_MP', '016', 'REVISTAS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (270, 'TIPOS_DE_ADJUNTOS_MP', '015', 'LIBROS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (269, 'TIPOS_DE_ADJUNTOS_MP', '014', 'CAJAS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (267, 'TIPOS_DE_ADJUNTOS_MP', '012', 'ANILLADO A4', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (266, 'TIPOS_DE_ADJUNTOS_MP', '011', 'PIONER A3', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (265, 'TIPOS_DE_ADJUNTOS_MP', '010', 'PIONER A4', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (264, 'TIPOS_DE_ADJUNTOS_MP', '009', 'USB', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (263, 'TIPOS_DE_ADJUNTOS_MP', '008', 'FOLDER', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (262, 'DIAS_LIMITE_AMBAR', '3', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (261, 'MENU', '25', 'DOCUMENTOS ANULADOS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (260, 'MENU', '24', 'DOCUMENTOS PENDIENTES', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (259, 'prefijonrotramiteproduccion', '000000', 'Formato de Nro de Tramite', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (258, 'INFRAESTRUCTURA', '9', 'JEF. FISCALIZACIÃ?N', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (257, 'INFRAESTRUCTURA', '8', 'LINEA 2', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (256, 'INFRAESTRUCTURA', '7', 'OTROS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (255, 'INFRAESTRUCTURA', '6', 'DATA ANTIGUA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (254, 'INFRAESTRUCTURA', '5', 'PUERTOS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (253, 'INFRAESTRUCTURA', '4', 'FERROCARRILES', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (252, 'INFRAESTRUCTURA', '3', 'CARRETERAS DEL SUR', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (251, 'INFRAESTRUCTURA', '2', 'CARRETERAS DEL NORTE Y CENTRO', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (250, 'INFRAESTRUCTURA', '1', 'AEROPUERTOS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (247, 'MATERIA', '7', 'MANTENIMIENTO', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (246, 'MATERIA', '6', 'SEGURIDAD', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (245, 'MATERIA', '5', 'MEDIO AMBIENTE', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (244, 'MATERIA', '4', 'DATA ANTIGUA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (243, 'MATERIA', '3', 'OPERACIONES', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (242, 'MATERIA', '2', 'INVERSIONES', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (241, 'MATERIA', '1', 'COMERCIAL', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (240, 'ADJUNTO_COPIA_ORIGINAL', '1', 'ORIGINAL', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (239, 'ADJUNTO_COPIA_ORIGINAL', '0', 'COPIA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (238, 'TIPOS_DE_ADJUNTOS_MP', '007', 'FOLLETOS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (237, 'TIPOS_DE_ADJUNTOS_MP', '006', 'TABLAS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (236, 'TIPOS_DE_ADJUNTOS_MP', '005', 'PLANOS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (235, 'TIPOS_DE_ADJUNTOS_MP', '004', 'ANILLADO A3', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (234, 'TIPOS_DE_ADJUNTOS_MP', '003', 'PIONER', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (233, 'TIPOS_DE_ADJUNTOS_MP', '002', 'ANILLADO', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (232, 'TIPOS_DE_ADJUNTOS_MP', '001', 'DISCOS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (231, 'UNIDAD_INFORME_CONJUNTO', '999', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (229, 'DESCARGAR_PENDIENTES', '13', 'Areas con permiso para descargar los pendientes', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (228, 'AREAS_CONSULTA_INTERNOS_TRAMITE', '276', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (224, 'CRITERIOS_CONFIDENCIAL', '05', 'Materia Expresamente Exceptuada por la Constituci¿ por una Ley', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (223, 'CRITERIOS_CONFIDENCIAL', '04', 'Informaci¿e Asesor Jur¿co de la APN sobre la Estrategia de Defensa en Proceso Administrativo o Judicial, o Secreto Profesional', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (222, 'CRITERIOS_CONFIDENCIAL', '03', 'Investigaci¿n T¿te sobre la Potestad Sancionadora de la Administraci¿¿ca', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (221, 'CRITERIOS_CONFIDENCIAL', '01', 'Secreto Bancario, Tributario, Comercial, Industrial, Tecnol¿o y Burs¿l', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (220, 'CRITERIOS_CONFIDENCIAL', '02', 'Consejos, Recomendaciones u Opiniones, Previo a la Toma de una Decisi¿e Gobierno', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (204, 'DOCUMENTOS_CONSULTA_INTERNOS_TRAMITE', '15', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (203, 'DOCUMENTOS_CONSULTA_INTERNOS_TRAMITE', '3', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (202, 'PROCESOS_CONSULTA_INTERNOS_TRAMITE', '100', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (182, 'MTC_TIP_DOCUMENTO', '188', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (181, 'MTC_TIP_DOCUMENTO', '100', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (180, 'MTC_AREA', '278', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (179, 'MTC_AREA', '255', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (164, 'PROCESOS_CONSULTA_EXTERNOS_TRAMITE', '101', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (163, 'PROCESOS_CONSULTA_EXTERNOS_TRAMITE', '15', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (162, 'PROCESOS_CONSULTA_EXTERNOS_TRAMITE', '14', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (161, 'PROCESOS_CONSULTA_EXTERNOS_TRAMITE', '13', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (160, 'PROCESOS_CONSULTA_EXTERNOS_TRAMITE', '12', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (159, 'PROCESOS_CONSULTA_EXTERNOS_TRAMITE', '11', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (158, 'PROCESOS_CONSULTA_EXTERNOS_TRAMITE', '10', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (157, 'PROCESOS_CONSULTA_EXTERNOS_TRAMITE', '9', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (156, 'PROCESOS_CONSULTA_EXTERNOS_TRAMITE', '8', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (155, 'PROCESOS_CONSULTA_EXTERNOS_TRAMITE', '7', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (154, 'PROCESOS_CONSULTA_EXTERNOS_TRAMITE', '6', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (153, 'PROCESOS_CONSULTA_EXTERNOS_TRAMITE', '5', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (152, 'PROCESOS_CONSULTA_EXTERNOS_TRAMITE', '4', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (151, 'PROCESOS_CONSULTA_EXTERNOS_TRAMITE', '3', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (150, 'PROCESOS_CONSULTA_EXTERNOS_TRAMITE', '2', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (149, 'FORMATO_AREA_GENERAR_DOCUMENTO', '273', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (148, 'FORMATO_AREA_GENERAR_DOCUMENTO', '178', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (147, 'MTC_TIP_DOCUMENTO', '3', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (146, 'MTC_TIP_DOCUMENTO', '2', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (145, 'MTC_TIP_DOCUMENTO', '86', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (144, 'MTC_TIP_DOCUMENTO', '1', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (143, 'MTC_AREA', '275', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (142, 'MTC_AREA', '273', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (141, 'MTC_AREA', '263', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (140, 'MTC_AREA', '286', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (139, 'MTC_AREA', '279', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (138, 'MTC_AREA', '277', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (137, 'MTC_AREA', '303', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (136, 'MTC_AREA', '256', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (135, 'MTC_AREA', '178', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (134, 'MTC_AREA', '249', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (133, 'MTC_AREA', '250', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (132, 'MTC_AREA', '252', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (131, 'PRIORIDAD_DIAS', '3', '3', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (130, 'PRIORIDAD_DIAS', '2', '5', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (129, 'PRIORIDAD_DIAS', '1', '7', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (128, 'PROCESOS_CONSULTA_EXTERNOS_TRAMITE', '1', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (127, 'DOCUMENTOS_CONSULTA_EXTERNOS_TRAMITE', '3', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (126, 'DOCUMENTOS_CONSULTA_EXTERNOS_TRAMITE', '15', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (116, 'AREAS_CONSULTA_EXTERNOS_TRAMITE', '1', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (115, 'SERVICIO_FEDATARIO', '2', 'Autenticaci¿e Firmas', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (114, 'SERVICIO_FEDATARIO', '1', 'Autenticaci¿e Documentos', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (113, 'FORMATO_NUMERACION_GERENCIA', '3', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (112, 'FORMATO_NUMERACION_GERENCIA', '1', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (111, 'DOCUMENTOS_PENDIENTES_GRUPO_AREA', '178092263', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (110, 'DOCUMENTOS_PENDIENTES_GRUPO_AREA', '178088286', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (109, 'DOCUMENTOS_PENDIENTES_GRUPO_AREA', '178089303', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (108, 'DOCUMENTOS_PENDIENTES_GRUPO_AREA', '178090256', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (107, 'DOCUMENTOS_PENDIENTES_GRUPO_AREA', '178091278', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (106, 'DOCUMENTOS_PENDIENTES_GRUPO_AREA', '178093279', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (105, 'DOCUMENTOS_PENDIENTES_GRUPO_AREA', '178094277', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (104, 'DOCUMENTOS_PENDIENTES_GRUPO_AREA', '178095252', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (103, 'DOCUMENTOS_PENDIENTES_GRUPO_AREA', '178096250', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (102, 'DOCUMENTOS_PENDIENTES_GRUPO_AREA', '178097249', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (101, 'DOCUMENTOS_PENDIENTES_GRUPO_AREA', '178098275', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (100, 'DOCUMENTOS_PENDIENTES_GRUPO_AREA', '178099178', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (99, 'DOCUMENTOS_PENDIENTES_GRUPO_AREA', '178100273', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (98, 'DESCARGAR_DOCUMENTOS_PENDIENTES_AREA', '178', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (97, 'MENU', '100', 'CORREO', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (96, 'MENU', '98', 'BUSQUEDA AVANZADA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (95, 'MENU', '77', 'BANDEJAS COMPARTIDAS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (94, 'MENU', '19', 'CARPETAS DE BUSQUEDA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (93, 'MENU', '20', 'CONSULTA DE DOCUMENTOS RECEPCIONADOS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (92, 'MENU', '3', 'MENSAJERIA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (91, 'MENU', '22', 'DOCUMENTOS IMPORTANTES', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (90, 'MENU', '18', 'ARCHIVADOS Y ATENDIDOS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (89, 'MENU', '9', 'INFORMATIVOS RECIBIDOS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (88, 'MENU', '2', 'DOCUMENTOS ENVIADOS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (87, 'MENU', '6', 'MIS DOCUMENTOS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (86, 'MENU', '0', 'DOCUMENTOS RECIBIDOS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (85, 'MAIL_FILEPATH_DOCUMENTO_MULTIPLE', 'multiple.txt', 'Plantilla para rechazar en correos electronicos', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (84, 'DESCARGAR_PENDIENTES', '18', 'Areas con permiso para descargar los pendientes', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (83, 'SEGUIMIENTO_ROL', '68', 'Rol para gerencia en la consulta del Seguimiento', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (82, 'ID_AUTOR_NUMERACION_PRESIDENCIA', '4057', 'id usuario para la numeracion de Presidencia, usado por otras areas', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (81, 'ID_AUTOR_NUMERACION_GERENCIA', '3836', 'id usuario para la numeracion de Gerencia,  usado por otras areas ', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (80, 'PLAZO_PARA_PRESIDENCIA', '1', 'Plazo para presidencia', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (79, 'PLAZO_PARA_GERENCIA', '1', 'Plazo para gerencia', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (78, 'usuario_mensajeria', 'MENSAJERO', 'Usuario que apareceren la traza como destinatario en la mensajeria', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (77, 'fechaDesdeBusquedaRapida2', '01/01/2017', 'Fecha Desde', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (76, 'fechaHastaBusquedaRapida', '31/12/2017', 'Fecha Hasta', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (75, 'fechaDesdeBusquedaRapida', '01/01/2017', 'Fecha Desde', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (74, 'MAIL_FILEPATH_LECTURA_EXPEDIENTE', 'lectura_expediente.txt', 'Correo que se envia cuando se lee un expediente', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (73, 'prioridad', '3', 'Muy Urgente', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (72, 'prioridad', '2', 'Urgente', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (71, 'prioridad', '1', 'Normal', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (69, 'MAIL_FILEPATH_DOCUMENTO_RECUPERAR', 'documento_recuperado.txt', 'Documento que se recupera de la bandeja del destinatario', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (68, 'MAIL_FILEPATH_DOCUMENTO_RECHAZAR', 'rechazar.txt', 'Plantilla para rechazar en correos electronicos', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (66, 'MAIL_FILEPATH_ENUMERACION_COPIA', 'ccreenviar.txt', 'Correo que se envia al enumerar un documento con copia', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (65, 'MAIL_FILEPATH_ENUMERACION_DESTINATARIO', 'enumeracion_destinatario.txt', 'Correo que se envia al enumerar un documento con destinatario', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (64, 'MAIL_FILEPATH_DOCUMENTO_CCAPROBAR', 'ccaprobar.txt', 'Correo que se envia al aprobar un documento con copia', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (63, 'MAIL_FILEPATH_DOCUMENTO_CCPORAPROBAR', 'ccporaprobar.txt', 'Correo que se envia al reenviar un documento por aprobar con copia', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (62, 'MAIL_FILEPATH_DOCUMENTO_CCREENVIAR', 'ccreenviar.txt', 'Correo que se envia al reenviar un documento con copia', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (61, 'MAIL_FILEPATH_DOCUMENTO_APROBAR', 'aprobar.txt', 'Correo que se envia al aprobar un documento', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (60, 'MAIL_FILEPATH_DOCUMENTO_PORAPROBAR', 'poraprobar.txt', 'Correo que se envia al reenviar un documento por aprobar', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (59, 'MAIL_FILEPATH_DOCUMENTO_REENVIAR', 'reenviar.txt', 'Correo que se envia al reenviar un documento', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (58, 'moneda', 'Dolares', 'Dolares', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (57, 'moneda', 'Nuevos Soles', 'Nuevos Soles', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (56, 'tiponotificacion', '1013', 'Expediente Enviado a OEFA', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (55, 'tipoProcesoProduccion', '* Ambiente ProducciÃ³n', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (54, 'tipoProcesoPiloto', '* Ambiente Piloto', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (53, 'tiponotificacion', '1012', 'Expediente Archivado', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (52, 'MAIL_FILEPATH_DOCUMENTO_ARCHIVADO', 'documento_archivado.txt', 'Correo que se envia cuando se archiva un documento', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (51, 'prefijonroexpedienteproduccion', '00000000', 'Prefijo usado para la generacion de nro de expediente en produccion', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (50, 'MAIL_FILEPATH_DERIVACION_CONCOPIA', 'derivacion_concopia.txt', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (49, 'bookmarkFirma', 'osifirma', 'Bookmark para la firma de documentos de tipo .doc', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (48, 'prefijonroexpediente', '201800000000', 'Prefijo usado para la generacion de nro de expediente', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (47, 'tiponotificacion', '1011', 'Referencia de Documento', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (45, 'tiponotificacion', '1022', 'Registro - Sancionador', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (44, 'tiponotificacion', '1021', 'Desaprado - Sancionador', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (43, 'tiponotificacion', '1020', 'Aprobado - Sancionador', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (42, 'test', '22', 'wedfwvsdv', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (41, 'MAIL_FILEPATH_ALARMA_ROJA', 'alarma_roja.txt', 'Correo cuando se lanza el evento de alarma roja', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (40, 'MAIL_FILEPATH_ALARMA_AMARILLA', 'alarma_amarilla.txt', 'Correo cuando se lanza el evento de alarma amarilla', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (39, 'MAIL_FILEPATH_INGRESO_DOCUMENTO_USERFINAL', 'ingreso_documento_user.txt', 'Correo cuando se lanza el evento de ingreso de documento por usuario final', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (38, 'MAIL_FILEPATH_INGRESO_DOCUMENTO_QAS', 'ingreso_documento_qas.txt', 'Correo cuando se lanza el evento de ingreso de documento por QAS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (37, 'MAIL_FILEPATH_CREACION_EXPEDIENTE', 'creacion_expediente.txt', 'Correo cuando se lanza el evento de creacion de expediente', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (36, 'MAX_SIZE_FILE', '41943040', '20 Mb', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (35, 'idusuariohistorico', '120', 'Usuario administrador de expedientes historicos', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (34, 'clasificar', 'detalle', 'Detalle', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (33, 'clasificar', 'resumen', 'Resumen', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (32, 'procesoClasificacion', 'proceso', 'Por Proceso', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (31, 'procesoClasificacion', 'grupoproceso', 'Por Grupo de Proceso', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (30, 'tiponotificacion', '314159', 'Rechazo', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (29, 'tiponotificacion', '555', 'Aprobacion QAS', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (28, 'tiponotificacion', '666', 'Derivacion', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (27, 'tiponotificacion', '1010', 'Nuevo Documento', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (26, 'tiponotificacion', '1009', 'Dueño Expediente', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (25, 'tiponotificacion', '1008', 'Rechazo Cambio de sala', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (24, 'tiponotificacion', '1007', 'Rechazo Resolucion SG', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (23, 'tiponotificacion', '1006', 'Rechazo Resolucion ST', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (22, 'tiponotificacion', '1005', 'Rechazo Legal', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (21, 'tiponotificacion', '1004', 'Rechazo Tecnico', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (20, 'tiponotificacion', '1003', 'Audiencia de Concialicion', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (19, 'tiponotificacion', '1002', 'Inspeccion de Campo', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (18, 'tiponotificacion', '1001', 'Adicional', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (17, 'tiponotificacion', '3', 'Notificacion de Usuario', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (16, 'tiponotificacion', '2', 'Notificacion Roja', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (15, 'tiponotificacion', '1', 'Notificacion Amarilla', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (14, 'MAIL_FILEPATH_DERIVAR', 'derivar.txt', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, ESTADO)
 Values
   (13, 'MAIL_FILEPATH_APROBAR', 'aprobar.txt', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (12, 'MAIL_ADMIN', 'siged@ositran.gob.pe', 'admin para mails', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (11, 'horaFinEnvio', '17:30', 'Hora de fin para el envio de archivos', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (10, 'horaInicioEnvio', '8:30', 'Hora de inicio para el envio de archivos', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (9, 'MARCADEAGUA', 'MARCA3', 'Marca 3', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (8, 'MARCADEAGUA', 'MARCA2', 'Marca 2', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (7, 'MARCADEAGUA', 'MARCA1', 'Marca 1', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, DESCRIPCION, ESTADO)
 Values
   (6, 'MARCADEAGUA', 'Sin Marca', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (3, 'FINHORARIO', '17:30', 'Fin de Horario para seguimiento', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (2, 'INICIOHORARIO', '8:00', 'Inicio de Horario para seguimiento', '1');
Insert into PARAMETRO
   (IDPARAMETRO, TIPO, VALOR, DESCRIPCION, ESTADO)
 Values
   (1, 'usuariostor', 'atramdoc', 'Usuario de Tramite Documentario', '1');
