 --SELECT NEXT VALUE FOR expediente_seq_prod
 CREATE SEQUENCE expediente_seq_prod START WITH 1 INCREMENT BY 1;
 CREATE SEQUENCE expediente_seq_dev START WITH 1 INCREMENT BY 1;
 CREATE SEQUENCE consulta_tramite_seq START WITH 1 INCREMENT BY 1;
 CREATE SEQUENCE documento_tramite_seq START WITH 1 INCREMENT BY 1;
 CREATE SEQUENCE nromp_tramite_seq START WITH 1 INCREMENT BY 1;
 CREATE SEQUENCE getnextmesapartes_seq START WITH 1 INCREMENT BY 1; 
 CREATE SEQUENCE tipoidentificacionotro_seq START WITH 1 INCREMENT BY 1; 
 
 