USE [siged]
GO

/****** Object:  Table [dbo].[COMPARTIDOXUSUARIO]    Script Date: 18/10/2021 23:50:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMPARTIDOXUSUARIO](
	[USUARIO] [int] NOT NULL,
	[ASIGNADO] [int] NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[COMPARTIDOXUSUARIO]  WITH CHECK ADD  CONSTRAINT [FK7BBC5CF66787C5F4] FOREIGN KEY([ASIGNADO])
REFERENCES [dbo].[usuario] ([idusuario])
GO

ALTER TABLE [dbo].[COMPARTIDOXUSUARIO] CHECK CONSTRAINT [FK7BBC5CF66787C5F4]
GO

ALTER TABLE [dbo].[COMPARTIDOXUSUARIO]  WITH CHECK ADD  CONSTRAINT [FK7BBC5CF686D252D4] FOREIGN KEY([USUARIO])
REFERENCES [dbo].[usuario] ([idusuario])
GO

ALTER TABLE [dbo].[COMPARTIDOXUSUARIO] CHECK CONSTRAINT [FK7BBC5CF686D252D4]
GO


