USE [siged]
GO

/****** Object:  Table [dbo].[DEPENDENCIAS]    Script Date: 18/10/2021 23:57:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DEPENDENCIAS](
	[COD_DEP] [int] NOT NULL,
	[DESCRIP] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[COD_DEP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


