USE [siged]
GO

/****** Object:  Table [dbo].[GRUPOPROCESO]    Script Date: 19/10/2021 18:59:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GRUPOPROCESO](
	[IDGRUPOPROCESO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO] [varchar](255) NOT NULL,
	[DESCRIPCION] [varchar](255) NULL,
	[ESTADO] [char](1) NULL,
	[FECHACREACION] [datetime] NULL,
	[NOMBRE] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDGRUPOPROCESO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


