USE [siged]
GO

/****** Object:  Table [dbo].[IOTDTC_DESPACHO]    Script Date: 19/10/2021 19:00:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IOTDTC_DESPACHO](
	[SIDEMIEXT] [int] IDENTITY(1,1) NOT NULL,
	[BCARSTDREC] [image] NULL,
	[CFLGENV] [char](1) NOT NULL,
	[CFLGEST] [char](1) NOT NULL,
	[CTIPDOCIDEREM] [char](1) NOT NULL,
	[DFECENV] [datetime] NULL,
	[DFECMOD] [datetime] NULL,
	[DFECREG] [datetime] NOT NULL,
	[DFECREGSTDREC] [datetime] NULL,
	[IDDOCUMENTO] [int] NOT NULL,
	[VANIOREGSTD] [varchar](255) NULL,
	[VANIOREGSTDREC] [varchar](255) NULL,
	[VCODUNIORGREM] [varchar](255) NULL,
	[VCUO] [varchar](255) NULL,
	[VCUOREF] [varchar](255) NULL,
	[VDESANXSTDREC] [varchar](255) NULL,
	[VNOMENTREC] [varchar](255) NOT NULL,
	[VNUMDOCIDEREM] [varchar](255) NOT NULL,
	[VNUMREGSTD] [varchar](255) NULL,
	[VNUMREGSTDREC] [varchar](255) NULL,
	[VOBS] [varchar](255) NULL,
	[VRUCENTREC] [varchar](255) NOT NULL,
	[VUNIORGREM] [varchar](255) NULL,
	[VUNIORGSTDREC] [varchar](255) NULL,
	[VUSUMOD] [varchar](255) NULL,
	[VUSUREG] [varchar](255) NOT NULL,
	[VUSUREGSTDREC] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[SIDEMIEXT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


