USE [siged]
GO

/****** Object:  Table [dbo].[IOTDTC_RECEPCION]    Script Date: 19/10/2021 19:00:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IOTDTC_RECEPCION](
	[SIDRECEXT] [int] NOT NULL,
	[BCARSTD] [image] NULL,
	[CCODUNIORGSTD] [varchar](255) NULL,
	[CFLGENVCAR] [char](1) NULL,
	[CFLGEST] [char](1) NOT NULL,
	[CFLGESTOBS] [char](1) NULL,
	[CTIPDOCIDEREM] [char](1) NOT NULL,
	[DFECMOD] [datetime] NULL,
	[DFECREG] [datetime] NOT NULL,
	[DFECREGSTD] [datetime] NULL,
	[IDDOCUMENTO] [int] NOT NULL,
	[VANIOREGSTD] [varchar](255) NULL,
	[VCUO] [varchar](255) NOT NULL,
	[VCUOREF] [varchar](255) NULL,
	[VDESANXSTD] [varchar](255) NULL,
	[VNUMDOCIDEREM] [varchar](255) NOT NULL,
	[VNUMREGSTD] [varchar](255) NULL,
	[VOBS] [varchar](255) NULL,
	[VRUCENTREM] [varchar](255) NOT NULL,
	[VUNIORGREM] [varchar](255) NOT NULL,
	[VUNIORGSTD] [varchar](255) NULL,
	[VUSUMOD] [varchar](255) NULL,
	[VUSUREGSTD] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[SIDRECEXT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


