USE [siged]
GO

/****** Object:  Table [dbo].[IOTDTM_DOC_EXTERNO]    Script Date: 19/10/2021 19:02:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IOTDTM_DOC_EXTERNO](
	[SIDDOCEXT] [int] IDENTITY(1,1) NOT NULL,
	[CCODTIPDOC] [varchar](255) NOT NULL,
	[CINDTUP] [char](1) NULL,
	[DFECDOC] [datetime] NOT NULL,
	[SNUMANX] [numeric](19, 2) NULL,
	[SNUMFOL] [numeric](19, 2) NOT NULL,
	[VASU] [varchar](255) NOT NULL,
	[VNOMCARDST] [varchar](255) NOT NULL,
	[VNOMDST] [varchar](255) NOT NULL,
	[VNOMENTEMI] [varchar](255) NOT NULL,
	[VNUMDOC] [varchar](255) NOT NULL,
	[VUNIORGDST] [varchar](255) NOT NULL,
	[VURLDOCANX] [varchar](255) NULL,
	[SIDEMIEXT] [int] NULL,
	[SIDRECEXT] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[SIDDOCEXT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[IOTDTM_DOC_EXTERNO]  WITH CHECK ADD  CONSTRAINT [FKB02057585CFB3702] FOREIGN KEY([SIDEMIEXT])
REFERENCES [dbo].[IOTDTC_DESPACHO] ([SIDEMIEXT])
GO

ALTER TABLE [dbo].[IOTDTM_DOC_EXTERNO] CHECK CONSTRAINT [FKB02057585CFB3702]
GO

ALTER TABLE [dbo].[IOTDTM_DOC_EXTERNO]  WITH CHECK ADD  CONSTRAINT [FKB0205758E650F552] FOREIGN KEY([SIDRECEXT])
REFERENCES [dbo].[IOTDTC_RECEPCION] ([SIDRECEXT])
GO

ALTER TABLE [dbo].[IOTDTM_DOC_EXTERNO] CHECK CONSTRAINT [FKB0205758E650F552]
GO


