USE [siged]
GO

/****** Object:  Table [dbo].[NUMERACIONEXPEDIENTE]    Script Date: 19/10/2021 19:12:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NUMERACIONEXPEDIENTE](
	[IDNUMERACIONEXPEDIENTE] [int] NOT NULL,
	[FORMATO] [varchar](255) NOT NULL,
	[NUMEROACTUAL] [int] NULL,
	[IDGRUPOPROCESO] [int] NULL,
	[IDPROCESO] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[IDNUMERACIONEXPEDIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[NUMERACIONEXPEDIENTE]  WITH CHECK ADD  CONSTRAINT [FKA9D038DAD5C9B7D3] FOREIGN KEY([IDPROCESO])
REFERENCES [dbo].[proceso] ([idproceso])
GO

ALTER TABLE [dbo].[NUMERACIONEXPEDIENTE] CHECK CONSTRAINT [FKA9D038DAD5C9B7D3]
GO

ALTER TABLE [dbo].[NUMERACIONEXPEDIENTE]  WITH CHECK ADD  CONSTRAINT [FKA9D038DAFDAACEE7] FOREIGN KEY([IDGRUPOPROCESO])
REFERENCES [dbo].[GRUPOPROCESO] ([IDGRUPOPROCESO])
GO

ALTER TABLE [dbo].[NUMERACIONEXPEDIENTE] CHECK CONSTRAINT [FKA9D038DAFDAACEE7]
GO


