USE [siged]
GO

/****** Object:  Table [dbo].[SUBMOTIVOXEXPEDIENTESTOR]    Script Date: 19/10/2021 19:42:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SUBMOTIVOXEXPEDIENTESTOR](
	[idexpediente] [int] NOT NULL,
	[idsubmotivo] [int] NOT NULL,
	[monto] [float] NULL,
	[moneda] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idexpediente] ASC,
	[idsubmotivo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SUBMOTIVOXEXPEDIENTESTOR]  WITH CHECK ADD  CONSTRAINT [FKAF8924F336F64D5D] FOREIGN KEY([idsubmotivo])
REFERENCES [dbo].[submotivo] ([idsubmotivo])
GO

ALTER TABLE [dbo].[SUBMOTIVOXEXPEDIENTESTOR] CHECK CONSTRAINT [FKAF8924F336F64D5D]
GO

ALTER TABLE [dbo].[SUBMOTIVOXEXPEDIENTESTOR]  WITH CHECK ADD  CONSTRAINT [FKAF8924F3C30DD8C7] FOREIGN KEY([moneda])
REFERENCES [dbo].[parametro] ([idparametro])
GO

ALTER TABLE [dbo].[SUBMOTIVOXEXPEDIENTESTOR] CHECK CONSTRAINT [FKAF8924F3C30DD8C7]
GO

ALTER TABLE [dbo].[SUBMOTIVOXEXPEDIENTESTOR]  WITH CHECK ADD  CONSTRAINT [FKAF8924F3C62415F5] FOREIGN KEY([idexpediente])
REFERENCES [dbo].[expedientestor] ([idexpediente])
GO

ALTER TABLE [dbo].[SUBMOTIVOXEXPEDIENTESTOR] CHECK CONSTRAINT [FKAF8924F3C62415F5]
GO


