SELECT * FROM TIPODOCUMENTO
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   ( 'CARTA DE INSTRUCCIONES DE PAGO', 'CARTA DE INSTRUCCIONES DE PAGO', 'A', 'CARTA_DE_INSTRUCCIONES_DE_PAGO', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'ACTA', 'ACTA', 'A', 'ACTA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'RESOLUCION', 'RESOLUCION', 'A', 'RESOLUCION', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'INVITACION', 'INVITACION', 'I', 'INVITACION', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'RENDICION Y-O REEMBOLSO DE GASTOS POR COMISION', 'RENDICION DE GASTOS - REEMBOLSO DE GASTOS POR COMISION DE SERVICIO', 'A', 'RENDICION_DE_GASTOS_REEMBOLSO_DE_GASTOS_COMISION', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'SOBRE CERRADO', 'SOBRE CERRADO', 'I', 'SOBRE_CERRADO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'ESTADOS CTAS', 'ESTADOS CTAS', 'I', 'ESTADOS_CTAS', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'ASIGNACION EN USO DE BIENES', 'ASIGNACION EN USO DE BIENES', 'A', 'ASIGNACION_EN_USO_DE_BIENES', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'C.VITAE', 'C.VITAE', 'A', 'C.VITAE', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'MEMORIAL', 'MEMORIAL', 'I', 'MEMORIAL', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'DESPLAZAMIENTO DE BIENES MUEBLES', 'DESPLAZAMIENTO DE BIENES MUEBLES', 'A', 'DESPLA_INT_EXT_BIENES_MUEBLES', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'RECIBO', 'RECIBO', 'A', 'RECIBO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'INGRESO-SALIDA DE BIENES DE PROPIEDAD PARTICULAR', 'INGRESO-SALIDA DE BIENES DE PROPIEDAD PARTICULAR', 'A', 'INGRESO_SALIDA_DE_BIENES_DE_PROPIEDAD_PARTICULAR', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'PEDIDO COMPROBANTE DE SALIDA - PECOSA', 'PEDIDO COMPROBANTE DE SALIDA - PECOSA', 'A', 'PEDIDO_COMPROBANTE_DE_SALIDA_PECOSA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'DESCANSO FISICO ANUAL POR VACACIONES', 'DESCANSO FISICO ANUAL POR VACACIONES', 'A', 'DESCANSO_FISICO_ANUAL_POR_VACACIONES', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'DECLARACION JURADA', 'DECLARACION JURADA', 'I', 'DECLARACION_JURADA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'ESQUELA', 'ESQUELA', 'I', 'ESQUELA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'NOTA DE CARGO', 'NOTA DE CARGO', 'I', 'NOTA_DE_CARGO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'NOTIFICACION', 'NOTIFICACION', 'A', 'NOTIFICACION', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'CONSTANCIA', 'CONSTANCIA', 'I', 'CONSTANCIA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'FORMULARIO', 'FORMULARIO', 'I', 'FORMULARIO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'BOLETIN', 'BOLETIN', 'I', 'BOLETIN', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'SOLICITUD', 'SOLICITUD', 'I', 'SOLICITUD', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'MEMORANDO CIRCULAR', 'MEMORANDO CIRCULAR', 'A', 'MEMORANDUM_CIRCULAR', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'CORREO ELECTRONICO', 'CORREO ELECTRONICO', 'I', 'CORREO_ELECTRONICO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'NOTA', 'NOTA', 'I', 'NOTA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'VARIOS', 'VARIOS', 'I', 'VARIOS', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'CERTIFICADO', 'CERTIFICADO', 'I', 'CERTIFICADO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'REG. PRESUPUESTAL', 'REG. PRESUPUESTAL', 'I', 'REG._PRESUPUESTAL', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'AVISO', 'AVISO', 'I', 'AVISO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'CITACION', 'CITACION', 'I', 'CITACION', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'ACTA DE CONFORMIDAD', 'ACTA DE CONFORMIDAD', 'A', 'ACTA_DE_CONFORMIDAD', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'ESCRITO', 'ESCRITO', 'A', 'ESCRITO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'XXX-MEMOS', 'XXX-MEMOS', 'I', 'XXX-MEMOS', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'CARTA OFICIO', 'CARTA OFICIO', 'I', 'CARTA_OFICIO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'NOTA TECNICA', 'NOTA TECNICA', 'I', 'NOTA_TECNICA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'ACTA DE REUNION LABORAL', 'ACTA DE REUNION LABORAL', 'I', 'ACTA_DE_REUNION_LABORAL', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, PIDE)
 Values
   ( 'CARTA MP', 'CARTA MP', 'A', 'CARTA', 
    'A', '02');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'CIRCULAR', 'CIRCULAR', 'I', 'CIRCULAR', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'COTIZACION-PROFORMA', 'COTIZACION-PROFORMA', 'I', 'COTIZACION-PROFORMA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'DIRECTIVA', 'DIRECTIVA', 'A', 'DIRECTIVA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'FOLLETO', 'FOLLETO', 'I', 'FOLLETO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'FACTURA', 'FACTURA', 'A', 'FACTURA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'INFORME', 'INFORME', 'A', 'INFORME', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'MEMORANDO', 'MEMORANDO', 'A', 'MEMORANDUM', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR, PIDE, ESTADOPIDE)
 Values
   ( 'OFICIO', 'OFICIO', 'A', 'OFICIO', 
    'A', '1', '1', '01', 'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   ( 'OFICIO CIRCULAR', 'OFICIO CIRCULAR', 'A', 'OFICIO_CIRCULAR', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   ( 'CARTA CIRCULAR', 'CARTA CIRCULAR', 'I', 'CARTA_CIRCULAR', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'ESTUDIO DE MERCADO', 'ESTUDIO DE MERCADO', 'I', 'ESTUDIO_DE_MERCADO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'CD-ROM', 'CD-ROM', 'I', 'CD-ROM', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'COMPROBANTE DE PAGO', 'COMPROBANTE DE PAGO', 'A', 'COMPROBANTE_DE_PAGO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'OFICIO MULTIPLE MP', 'OFICIO MULTIPLE MP', 'A', 'OFICIO_MULTIPLE', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   ( 'CONSTANCIA DE PRESTACION', 'CONSTANCIA DE PRESTACION', 'A', 'CONSTANCIA_DE_PRESTACION', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   ( 'CARTA NOTARIAL', 'CARTA NOTARIAL', 'A', 'CARTA_NOTARIAL', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'RESOLUCION DIRECTORAL', 'RESOLUCION DIRECTORAL', 'A', 'RESOLUCION_DIRECTORAL', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'COMUNICADO', 'COMUNICADO', 'I', 'COMUNICADO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'CARTA MULTIPLE', 'CARTA MULTIPLE', 'I', 'CARTA_MULTIPLE', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'AFICHE', 'AFICHE', 'I', 'AFICHE', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'SOLICITUD INF. PUBLICA', 'SOLICITUD INF. PUBLICA', 'A', 'SOLICITUD_INF._PUBLICA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'TUPA04-PROCEDIMIENTO DE FIJACIÓN Y RE', 'TUPA04-PROCEDIMIENTO DE FIJACION Y RE', 'A', 'TUPA04-PROCEDIMIENTO_DE_FIJACIÓN_Y_RE', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'TUPA05-PROCEDIMIENTO DE FIJACIÓN TARI', 'TUPA05-PROCEDIMIENTO DE FIJACION TARI', 'A', 'TUPA05-PROCEDIMIENTO_DE_FIJACION_TARI', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'TUPA06-PROCEDIMIENTO DE DESREGULARIZA', 'TUPA06-PROCEDIMIENTO DE DESREGULARIZA', 'A', 'TUPA06-PROCEDIMIENTO_DE_DESREGULARIZA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'TUPA07-PROCEDIMIENTO DE EMISOSN DE MA', 'TUPA07-PROCEDIMIENTO DE EMISOSN DE MA', 'A', 'TUPA07-PROCEDIMIENTO_DE_EMISOSN_DE_MA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'TUPA08-PROCEDIMIENTO DE CUESTIONAMIEN', 'TUPA08-PROCEDIMIENTO DE CUESTIONAMIEN', 'A', 'TUPA08-PROCEDIMIENTO_DE_CUESTIONAMIEN', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'TUPA09-PROCEDIMIENTO DE IMPUGNACIÓN D', 'TUPA09-PROCEDIMIENTO DE IMPUGNACION D', 'A', 'TUPA09-PROCEDIMIENTO_DE_IMPUGNACION_D', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'TUPA10-PROCEDIMIENTO DE IMPUGNACION D', 'TUPA10-PROCEDIMIENTO DE IMPUGNACION D', 'A', 'TUPA10-PROCEDIMIENTO_DE_IMPUGNACION_D', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'TUPA12-PROCEDIMIENTO DE QUEJA CONTRA LOS DEFECTOS ', 'TUPA12-PROCEDIMIENTO DE QUEJA CONTRA LOS DEFECTOS ', 'A', 'TUPA12-PROCEDIMIENTO_DE_QUEJA_CONTRA_LOS_DEFECTOS_', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'TUPA13-PROCEDMIENTO DE SOLUCION DE CONTROVERSIAS E', 'TUPA13-PROCEDMIENTO DE SOLUCION DE CONTROVERSIAS E', 'A', 'TUPA13-PROCEDMIENTO_DE_SOLUCIÓN_DE_CONTROVERSIAS_E', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'TUPA14-PROCEDIMIENTO DE IMPUGNACION DE LA DECISION', 'TUPA14-PROCEDIMIENTO DE IMPUGNACION DE LA DECISION', 'A', 'TUPA14-PROCEDIMIENTO_DE_IMPUGNACIÓN_DE_LA_DECISIÓN', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'TUPA15-PROCEDIMIENTO DE IMPUGNACIÓN DE LA DENEGATO', 'TUPA15-PROCEDIMIENTO DE IMPUGNACIÓN DE LA DENEGATO', 'A', 'TUPA15-PROCEDIMIENTO_DE_IMPUGNACIÓN_DE_LA_DENEGATO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'HOJA LIQUIDACION PAGO', 'HOJA LIQUIDACION PAGO', 'I', 'HOJA_LIQUIDACION_PAGO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'CONSULTA PUB.-PORTAL USU.', 'CONSULTA PUB.-PORTAL USU.', 'I', 'CONSULTA_PUB.-PORTAL_USU.', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'SUGERENCIA-PORTAL USU.', 'SUGERENCIA-PORTAL USU.', 'I', 'SUGERENCIA-PORTAL_USU.', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'DENUNCIA PUB.-PORTAL USU.', 'DENUNCIA PUB.-PORTAL USU.', 'I', 'DENUNCIA_PUB.-PORTAL_USU.', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'INF. TEC. EV. SOFT.', 'INF. TEC. EV. SOFT.', 'I', 'INFTECEVSOFT', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'NOTA DE CREDITO', 'NOTA DE CREDITO', 'A', 'NOTA_CREDITO_ELECTRONICA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'INFORME TECNICO', 'INFORME TECNICO', 'I', 'INFORME_TECNICO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'NOTA DE DEVENGADO', 'NOTA DE DEVENGADO', 'A', 'NOTA_DE_DEVENGADO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'NOTA DE DEVOLUCION', 'NOTA DE DEVOLUCION', 'A', 'NOTA_DE_DEVOLUCION', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'CONTROL DE PAGOS', 'CONTROL DE PAGOS ', 'A', 'CONTROL_DE_PAGOS', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'MEMORANDO CONJUNTO', 'MEMORANDO CONJUNTO', 'A', 'MEMORANDO_CONJUNTO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'ACTA DE SESION DE CONSEJO DIRECTIVO', 'ACTA DE SESION DE CONSEJO DIRECTIVO', 'A', 'ACTA_DE_SESION_DE_CONSEJO_DIRECTIVO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'ACTA DE CUERPO COLEGIADO', 'ACTA DE CUERPO COLEGIADO', 'A', 'ACTA_DE_CUERPO_COLEGIADO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'AGENDA DE SESION', 'AGENDA DE SESION', 'A', 'AGENDA_DE_SESION', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'FEDEX', 'FEDEX', 'I', 'FEDEX', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'CARTA FIANZA', 'CARTA FIANZA', 'I', 'CARTA_FIANZA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'NOTA CIRCULAR', 'NOTA CIRCULAR', 'I', 'NOTA_CIRCULAR', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'INFORME CONJUNTO', 'INFORME CONJUNTO', 'A', 'INFORME_CONJUNTO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'PAPELETA DE INFRACCION', 'PAPELETA DE INFRACCION', 'I', 'PAPELETA_DE_INFRACCION', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'NOTA DE OPERACION', 'NOTA DE OPERACION', 'I', 'NOTA_DE_OPERACION', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'FACTURA ELECTRONICA', 'FACTURA ELECTRONICA', 'A', 'FACTURA_ELECTRONICA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, SICOR)
 Values
   ( 'AGENDAS DE INSPECCION', 'AGENDAS DE INSPECCION', 'A', 'AGENDAS_DE_INSPECCION', 
    'A', '1');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'ACTAS DE INSPECCION', 'ACTAS DE INSPECCION', 'A', 'ACTAS_DE_INSPECCION', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, SICOR)
 Values
   ( 'ACTA DE REUNION DE TRAB.', 'ACTA DE REUNION DE TRAB.', 'A', 'ACTA_DE_REUNION_DE_TRAB', 
    'A', '1');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, SICOR)
 Values
   ( 'AGENDA DE REUNION DE TRAB.', 'AGENDA DE REUNION DE TRAB.', 'A', 'AGENDA_DE_REUNION_DE_TRAB', 
    'A', '1');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'MANDATOS DE ACCESO', 'MANDATOS DE ACCESO', 'I', 'MANDATOS_DE_ACCESO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'PROVEIDO', 'PROVEIDO', 'I', 'PROVEIDO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'HOJA DE RECLAMACION', 'HOJA DE RECLAMACION', 'A', 'HOJA_DE_RECLAMACION', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'INDAGACIÓN DE MERCADO', 'INDAGACIÓN DE MERCADO', 'I', 'INDAGACIÓN_DE_MERCADO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'CARGO DE ENTREGA', 'CARGO DE ENTREGA', 'I', 'CARGO_DE_ENTREGA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'TUPA01-PROCEDIMIENTO PARA LA CALIFICA', 'TUPA01-PROCEDIMIENTO PARA LA CALIFICA', 'A', 'TUPA01-PROCEDIMIENTO_PARA_LA_CALIFICA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'TUPA02-SOLICITUD DE ACCESO A LA INFOR', 'TUPA02-SOLICITUD DE ACCESO A LA INFOR', 'A', 'TUPA02-SOLICITUD_DE_ACCESO_A_LA_INFOR', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'TUPA03-PROCEDIMIENTO PARA LA INTERPRE', 'TUPA03-PROCEDIMIENTO PARA LA INTERPRE', 'A', 'TUPA03-PROCEDIMIENTO_PARA_LA_INTERPRE', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'CARTA ORDEN', 'CARTA ORDEN', 'A', 'CARTA_ORDEN', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'CARTA ORDEN ELECTRONICA', 'CARTA ORDEN ELECTRONICA', 'A', 'CARTA_ORDEN_ELECTRONICA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'REPORTE', 'REPORTE', 'A', 'REPORTE', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   ( 'RESOLUCION DE DETERMINACION', 'RESOLUCION DE DETERMINACION', 'A', 'RESOLUCION_DETERMINACION', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'ORDEN DE PAGO', 'ORDEN DE PAGO', 'A', 'ORDEN_PAGO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'APROBACION DE EXPEDIENTE DE CONTRATACION', 'APROBACION DE EXPEDIENTE DE CONTRATACION', 'A', 'APROBACION_EXPEDIENTE_CONTRATACION', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'DESIGNACION DE COMITE DE SELECCION', 'DESIGNACION DE COMITE DE SELECCION', 'A', 'DESIGNACION_COMITE_SELECCION', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'APROBACION DE DOCUMENTOS DEL PROCEDIMIENTO DE SELECCION', 'APROBACION DE DOCUMENTOS DEL PROCEDIMIENTO DE SELECCION', 'A', 'APROBACION_DOCUMENTOS_PROCEDIMIENTO_SELECCION', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'FORMULARIO DE CREACION DE SIGLAS EN EL SGD', 'FORMULARIO DE CREACION DE SIGLAS EN EL SGD', 'A', 'FORM_SIGLAS', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'FORMULARIO DE CREACION DE NUEVOS TIPOS DOC', 'FORMULARIO DE CREACION DE NUEVOS TIPOS DOC', 'A', 'FORM_TIPOS', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'HABILITACION Y CERTIFICACION PRESUPUESTAL', 'HABILITACION Y CERTIFICACION PRESUPUESTAL', 'A', 'HABILITACION_CERTIFICACION_PRESUPUESTAL', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'ESTADO DE CUENTA', 'ESTADO DE CUENTA', 'A', 'ESTADO_DE_CUENTA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   ( 'RESOLUCION DE MULTA', 'RESOLUCION DE MULTA', 'A', 'RESOLUCION_DE_MULTA', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'PEDIDO DE SERVICIO', 'PEDIDO DE SERVICIO', 'A', 'PEDIDO_DE_SERVICIO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'PEDIDO DE COMPRA', 'PEDIDO DE COMPRA', 'A', 'PEDIDO_DE_COMPRA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   ( 'ORDEN DE SERVICIO', 'ORDEN DE SERVICIO', 'A', 'ORDEN_DE_SERVICIO', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   ( 'ORDEN DE COMPRA', 'ORDEN DE COMPRA', 'A', 'ORDEN_DE_COMPRA', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'CEDULA DE COMUNICACION', 'CEDULA DE COMUNICACION', 'A', 'CEDULA_DE_COMUNICACION', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'REPORTE DE INFORMACION', 'REPORTE DE INFORMACION', 'A', 'REPORTE_DE_INFORMACION', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'RENDICION DE FONDOS DE CAJA CHICA', 'RENDICION DE FONDOS DE CAJA CHICA', 'A', 'RENDICION_DE_FONDOS_DE_CAJA_CHICA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'RECIBO DE INGRESO', 'RECIBO DE INGRESO', 'A', 'RECIBO_DE_INGRESO', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'FORMULARIO DE DENUNCIAS', 'FORMULARIO DE DENUNCIAS', 'A', 'FORMULARIO_DENUNCIAS', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'NOTA DE CERTIFICADO PRESUPUESTAL', 'NOTA DE CERTIFICADO PRESUPUESTAL', 'A', 'NOTA_DE_CERTIFICADO_PRESUPUESTAL', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'NOTA DE HABILITACION PRESUPUESTAL', 'NOTA DE HABILITACION PRESUPUESTAL', 'A', 'NOTA_DE_HABILITACION_PRESUPUESTAL', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'CUADRO COMPARATIVO DE PRECIOS', 'CUADRO COMPARATIVO DE PRECIOS', 'A', 'CUADRO_COMPARATIVO_DE_PRECIOS', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'HOJA INFORMATIVA', 'HOJA INFORMATIVA', 'A', 'HOJA_INFORMATIVA', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'CEDULA DE COMUNICACION', 'CEDULA DE COMUNICACION', 'A', 'CEDULA_DE_COMUNICACION', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   ( 'NOTA CONTABLE', 'NOTA CONTABLE', 'A', 'NOTA_CONTABLE', 
    'A');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   ( 'REQUERIMIENTO TRIBUTARIO', 'REQUERIMIENTO TRIBUTARIO', 'A', 'REQUERIMIENTO_TRIBUTARIO', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   ( NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   ( 'RESULTADO DE REQUERIMIENTO TRIBUTARIO', 'RESULTADO DE REQUERIMIENTO TRIBUTARIO', 'A', 'RESULTADO_REQUERIMIENTO_TRIBUTARIO', 
    'A', '1', '1');

