USE [siged]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ADMINISTRADORXUSUARIO](
	[USUARIO] [int] NOT NULL,
	[ADMINISTRADOR] [int] NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ADMINISTRADORXUSUARIO]  WITH CHECK ADD  CONSTRAINT [FK689F9D5367DCE663] FOREIGN KEY([ADMINISTRADOR])
REFERENCES [dbo].[usuario] ([idusuario])
GO

ALTER TABLE [dbo].[ADMINISTRADORXUSUARIO] CHECK CONSTRAINT [FK689F9D5367DCE663]
GO

ALTER TABLE [dbo].[ADMINISTRADORXUSUARIO]  WITH CHECK ADD  CONSTRAINT [FK689F9D5386D252D4] FOREIGN KEY([USUARIO])
REFERENCES [dbo].[usuario] ([idusuario])
GO

ALTER TABLE [dbo].[ADMINISTRADORXUSUARIO] CHECK CONSTRAINT [FK689F9D5386D252D4]
GO


