USE [siged]
GO

/****** Object:  Table [dbo].[IOTDTD_DOC_PRINCIPAL]    Script Date: 19/10/2021 19:02:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IOTDTD_DOC_PRINCIPAL](
	[SIDDOCPRI] [int] IDENTITY(1,1) NOT NULL,
	[BPDFDOC] [image] NOT NULL,
	[CCODEST] [char](1) NOT NULL,
	[DFECREG] [datetime] NOT NULL,
	[VNOMDOC] [varchar](255) NOT NULL,
	[SIDDOCEXT] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SIDDOCPRI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[IOTDTD_DOC_PRINCIPAL]  WITH CHECK ADD  CONSTRAINT [FKB8FC542EC4A237A5] FOREIGN KEY([SIDDOCEXT])
REFERENCES [dbo].[IOTDTM_DOC_EXTERNO] ([SIDDOCEXT])
GO

ALTER TABLE [dbo].[IOTDTD_DOC_PRINCIPAL] CHECK CONSTRAINT [FKB8FC542EC4A237A5]
GO


