USE [siged]
GO

/****** Object:  Table [dbo].[IOTDTD_ANEXO]    Script Date: 19/10/2021 19:01:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IOTDTD_ANEXO](
	[SIDDOCANX] [int] IDENTITY(1,1) NOT NULL,
	[DFECREG] [datetime] NOT NULL,
	[VNOMDOC] [varchar](255) NOT NULL,
	[SIDDOCEXT] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SIDDOCANX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[IOTDTD_ANEXO]  WITH CHECK ADD  CONSTRAINT [FK77614036C4A237A5] FOREIGN KEY([SIDDOCEXT])
REFERENCES [dbo].[IOTDTM_DOC_EXTERNO] ([SIDDOCEXT])
GO

ALTER TABLE [dbo].[IOTDTD_ANEXO] CHECK CONSTRAINT [FK77614036C4A237A5]
GO


