USE [siged]
GO

/****** Object:  Table [dbo].[SEG_M_ROL]    Script Date: 19/10/2021 19:35:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SEG_M_ROL](
	[ROL_ID] [int] NOT NULL,
	[ROL_NOMBRE] [varchar](255) NULL,
	[ROL_ESTADO] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ROL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


