USE [siged]
GO

/****** Object:  Table [dbo].[TRAZABILIDADCOPIA]    Script Date: 19/10/2021 22:31:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TRAZABILIDADCOPIA](
	[idtrazabilidadcopia] [int] IDENTITY(1,1) NOT NULL,
	[cargodestinatario] [int] NULL,
	[cargoremitente] [int] NULL,
	[fechacreacion] [datetime] NOT NULL,
	[nombrepc] [varchar](255) NULL,
	[tipo] [char](1) NOT NULL,
	[unidaddestinatario] [int] NULL,
	[unidadremitente] [int] NULL,
	[usuariocreacion] [int] NULL,
	[accion] [int] NOT NULL,
	[destinatario] [int] NOT NULL,
	[documento] [int] NOT NULL,
	[idetapa] [int] NULL,
	[idorigen] [int] NOT NULL,
	[idnotificacion] [int] NULL,
	[remitente] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idtrazabilidadcopia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TRAZABILIDADCOPIA]  WITH CHECK ADD  CONSTRAINT [FK3CE20B633CBC0577] FOREIGN KEY([destinatario])
REFERENCES [dbo].[usuario] ([idusuario])
GO

ALTER TABLE [dbo].[TRAZABILIDADCOPIA] CHECK CONSTRAINT [FK3CE20B633CBC0577]
GO

ALTER TABLE [dbo].[TRAZABILIDADCOPIA]  WITH CHECK ADD  CONSTRAINT [FK3CE20B635B2BAC56] FOREIGN KEY([accion])
REFERENCES [dbo].[accion] ([idaccion])
GO

ALTER TABLE [dbo].[TRAZABILIDADCOPIA] CHECK CONSTRAINT [FK3CE20B635B2BAC56]
GO

ALTER TABLE [dbo].[TRAZABILIDADCOPIA]  WITH CHECK ADD  CONSTRAINT [FK3CE20B63808C785B] FOREIGN KEY([idnotificacion])
REFERENCES [dbo].[notificacion] ([idnotificacion])
GO

ALTER TABLE [dbo].[TRAZABILIDADCOPIA] CHECK CONSTRAINT [FK3CE20B63808C785B]
GO

ALTER TABLE [dbo].[TRAZABILIDADCOPIA]  WITH CHECK ADD  CONSTRAINT [FK3CE20B63D0D3D145] FOREIGN KEY([remitente])
REFERENCES [dbo].[usuario] ([idusuario])
GO

ALTER TABLE [dbo].[TRAZABILIDADCOPIA] CHECK CONSTRAINT [FK3CE20B63D0D3D145]
GO

ALTER TABLE [dbo].[TRAZABILIDADCOPIA]  WITH CHECK ADD  CONSTRAINT [FK3CE20B63ECE70C43] FOREIGN KEY([idetapa])
REFERENCES [dbo].[etapa] ([idetapa])
GO

ALTER TABLE [dbo].[TRAZABILIDADCOPIA] CHECK CONSTRAINT [FK3CE20B63ECE70C43]
GO

ALTER TABLE [dbo].[TRAZABILIDADCOPIA]  WITH CHECK ADD  CONSTRAINT [FK3CE20B63F3722B18] FOREIGN KEY([idorigen])
REFERENCES [dbo].[trazabilidaddocumento] ([idtrazabilidaddocumento])
GO

ALTER TABLE [dbo].[TRAZABILIDADCOPIA] CHECK CONSTRAINT [FK3CE20B63F3722B18]
GO

ALTER TABLE [dbo].[TRAZABILIDADCOPIA]  WITH CHECK ADD  CONSTRAINT [FK3CE20B63FEB9D3E0] FOREIGN KEY([documento])
REFERENCES [dbo].[documento] ([iddocumento])
GO

ALTER TABLE [dbo].[TRAZABILIDADCOPIA] CHECK CONSTRAINT [FK3CE20B63FEB9D3E0]
GO


