USE [siged]
GO

/****** Object:  Table [dbo].[USUARIOXUNIDADXFUNCION]    Script Date: 19/10/2021 22:39:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USUARIOXUNIDADXFUNCION](
	[IDUSUARIO] [int] NULL,
	[IDUNIDAD] [int] NULL,
	[IDFUNCION] [int] NULL,
	[IDUSUARIOCARGO] [int] NULL,
	[ESTADO] [varchar](2) NULL,
	[USUARIOFINAL] [varchar](2) NULL,
	[IDROL] [int] NULL,
	[IDCARGOS] [int] NULL
) ON [PRIMARY]
GO


