--select * from SERIE;

-- DELETE FROM SERIE;
--COMMIT;

Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (1, 'GENERICO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (2, 'ACTAS DE ARQUEO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (3, 'ACTAS DE INSPECCION', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (4, 'ACTAS DE REUNIONES DE TRABAJO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (5, 'ACTOS DE INVESTIGACION INTERNA/F. SOLICITUDES DE ANTECEDENTES DE PROCESOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (6, 'ANUARIOS ESTADISTICOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (7, 'AUDITORIAS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (8, 'AUDITORIAS DEL SISTEMA DE GESTION DE CALIDAD', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (9, 'BOLETAS DE PAGO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (10, 'CAPACITACIONES DEL PERSONAL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (11, 'CLIMA ORGANIZACIONAL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (12, 'COMPROMISOS DE CONFIDENCIALIDAD', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (13, 'CONCILIACIONES BANCARIAS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (14, 'CONSTANCIAS DE PRESTACION', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (15, 'CONSTANCIAS DE PRESTAMO DE DOCUMENTOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (16, 'CONTABILIDAD REGULATORIA', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (17, 'CONTRATOS DE BIENES Y SERVICIOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (18, 'CONTROL DE DOCUMENTOS EN MESA DE PARTES', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (19, 'CONTROLES DE ALMACEN', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (20, 'CONVENIOS INSTERISTITUCIONALES', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (21, 'COPIAS INFORMATIVAS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (22, 'CORRESPONDENCIA', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (23, 'CRONOGRAMA ANUAL DE ELIMINACION', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (24, 'CRONOGRAMA ANUAL DE TRANSFERENCIA', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (25, 'CUADROS CONSOLIDADOS DE NECESIDADES', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (26, 'CURSOS DE EXTENSION UNIVERSITARIA', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (27, 'DECLARACIONES JURADAS DE INGRESOS, BIENES Y RENTAS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (28, 'DECLARACIONES TRIBUTARIAS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (29, 'DESPLAZAMIENTOS DE PERSONAL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (30, 'DIFUSION Y POSICIONAMIENTO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (31, 'DOCUMENTOS DE GESTION DE RECURSOS HUMANOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (32, 'ESTADOS DE CUENTA', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (33, 'ESTADOS FINANCIEROS Y PRESUPUESTALES', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (34, 'ESTUDIOS DE EVALUACION DE CALIDAD DE SERVICIOS AL USUARIO FINAL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (35, 'ESTUDIOS DE EVALUACION DE CALIDAD DE SERVICIOS AL USUARIO INTERMEDIO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (36, 'EVALUACIONES DE DESEMPEÑO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (37, 'EXPEDIENTES DE AUDIENCIAS PÚBLICAS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (38, 'EXPEDIENTES DE CERTIFICACION PRESUPUESTARIA', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (39, 'EXPEDIENTES DE CONFORMIDADES DE BIENES Y/O SERVICIOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (40, 'EXPEDIENTES DE CONTRATACION/PROCESOS DE SELECCIÓN', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (41, 'EXPEDIENTES DE CONTROVERSIAS Y RECLAMOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (42, 'EXPEDIENTES DE CUERPOS COLEGIADOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (43, 'EXPEDIENTES DE ELIMINACION DE DOCUMENTOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (44, 'EXPEDIENTES DE LA MEMORIA INSTITUCIONAL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (45, 'EXPEDIENTES DE PAGOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (46, 'EXPEDIENTES DE PENALIDADES', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (47, 'EXPEDIENTES DE PROCEDIMIENTOS ADMINISTRATIVOS DISCIPLINARIOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (48, 'EXPEDIENTES DE PROCEDIMIENTOS ADMINISTRATIVOS SANCIONADORES', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (49, 'EXPEDIENTES DE PROCESOS DE SELECCIÓN DE PERSONAL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (50, 'EXPEDIENTES DE PROCESOS ELECTORALES DE CONSEJOS DE USUARIOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (51, 'EXPEDIENTES DE RESOLUCIONES DE CONSEJO DIRECTIVO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (52, 'EXPEDIENTES DE RESOLUCIONES DE PRESIDENCIA', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (53, 'EXPEDIENTES EN ASUNTOS ADMINISTRATIVOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (54, 'EXPEDIENTES TECNICOS DE PROYECTOS DE INVERSION', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (55, 'FORMACION LABORAL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (56, 'FORMULACIONES DE PLANES INSTITUCIONALES', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (57, 'GESTIONES DE BIBLIOTECA', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (58, 'GESTIONES DEL BIENESTAR SOCIAL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (59, 'INDUCCIONES DE PERSONAL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (60, 'INFORMACION PARA PUBLICAR EN WEB', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (61, 'INFORMES  DE HALLAZGOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (62, 'INFORMES DE ACCIONES DE SEGURIDAD INFORMATICA', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (63, 'INFORMES DE ACTIVIDADES DE AUDIENCIAS PÚBLICAS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (64, 'INFORMES DE CONTROL PATRIMONIAL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (65, 'INFORMES DE CUMPLIMIENTOS DE HITOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (66, 'INFORMES DE DESEMPEÑO TARIFARIO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (67, 'INFORMES DE EJECUCION DEL PLAN ESTRATÉGICO DE TECNOLOGIAS DE LA INFORMACION', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (68, 'INFORMES DE EMPRESAS CONCESIONARIAS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (69, 'INFORMES DE HALLAZGOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (70, 'INFORMES DE INDAGACION DE MERCADO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (71, 'INFORMES DE MONITOREO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (72, 'INFORMES DE OPINION', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (73, 'INFORMES DE OPINION DE CONTRATOS DE CONCESION', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (74, 'INFORMES DE OPINION JURIDICO CONTRACTUALES', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (75, 'INFORMES DE OPINION JURIDICO REGULATORIOS Y ADMINISTRATIVOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (76, 'INFORMES DE OPINION SOBRE ENDEUDAMIENTO GARANTIZADO PERMITIDO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (77, 'INFORMES DE RUEDA DE PRENSA', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (78, 'INFORMES DE SUPERVISION', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (79, 'INFORMES TECNICOS DE OPINION', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (80, 'INFORMES TECNICOS DE REGULACION TARIFARIA', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (81, 'INGRESOS Y SALIDAS DEL PERSONAL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (82, 'INSTRUCCIONES DE PAGO DE FIDEICOMISOS/ CARTAS DE FIDEICOMISOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (83, 'INSTRUMENTOS DE GESTION ARCHIVISTICA', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (84, 'INVENTARIO DE LICENCIAS DE SOFTWARE', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (85, 'INVENTARIO GENERAL DE DOCUMENTOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (86, 'INVENTARIOS DE BIENES DE CONCESION', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (87, 'INVENTARIOS DE TRANSFERENCIA', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (88, 'LEGAJOS DEL SERVIDOR CIVIL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (89, 'LIBROS DE ACTAS DE SESIONES DE CUERPOS COLEGIADOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (90, 'LIBROS DE OBRA', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (91, 'LIQUIDACION DE BENEFICIOS SOCIALES', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (92, 'MANUAL DEL SISTEMA DE GESTION DE CALIDAD', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (93, 'MANUALES TECNICOS DE RECURSOS INFORMATICOS/ F. MANUALES DE OPERACIÓN DE REDES', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (94, 'NOTAS CONTABLES', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (95, 'ORDENES DE COMPRA Y SERVICIOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (96, 'PAGO DE LAUDO ARBITRAL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (97, 'PAGO DE VALORIZACIONES', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (98, 'PLAN ANUAL DE CONTRATACIONES', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (99, 'PLAN ANUAL DE CONTROL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (100, 'PLAN ANUAL DE SUPERVISION', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (101, 'PLAN DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (102, 'PLAN ESTRATEGICO DE TECNOLOGIAS DE LA INFORMACION', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (103, 'PLAN OPERATIVO INFORMATICO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (104, 'PLANES DE EMPRESAS CONCESIONARIAS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (105, 'PLANES DE MANTENIMIENTO PREVENTIVO CORRECTIVO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (106, 'PLANILLAS DE PAGO ', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (107, 'POLIZAS DE SEGUROS DE SALUD', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (108, 'PRESUPUESTO ANUAL INSTITUCIONAL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (109, 'PREVISIONES DEL CREDITO PRESUPUESTARIO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (110, 'PROGRAMAS DE MANTENIMIENTO INSTITUCIONAL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (111, 'RECIBOS DE INGRESOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (112, 'REGISTRO DE ACCESO A RECURSOS INFORMATICOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (113, 'REGISTROS - LIBROS CONTABLES', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (114, 'REGISTROS DE CONTROL DE ASISTENCIA', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (115, 'REGISTROS DE INFORMACION CONFIDENCIAL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (116, 'REGISTROS DE INSTALACION DE SOFTWARE', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (117, 'REQUERIMIENTO DE BIENES Y/O SERVICIOS INFORMATICOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (118, 'RESOLUCIONES DE CONSEJO DIRECTIVO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (119, 'RESOLUCIONES DE CUERPOS COLEGIADOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (120, 'RESOLUCIONES DE GERENCIA DE REGULACION Y ESTUDIOS ECONOMICOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (121, 'RESOLUCIONES DE GERENCIA DE SUPERVISION Y FISCALIZACION', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (122, 'RESOLUCIONES DE GERENCIA GENERAL', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (123, 'RESOLUCIONES DE LA GERENCIA DE ADMINISTRACION', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (124, 'RESOLUCIONES DE PRESIDENCIA', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (125, 'RESOLUCIONES DEL TRIBUNAL DE SOLUCION DE CONTROVERSIAS Y ATENCION DE RECLAMOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (126, 'RESOLUCIONES DEL TRIBUNAL EN ASUNTOS ADMINISTRATIVOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (127, 'SEGUIMIENTO DE ASPECTOS ADMINISTRATIVOS Y FINANCIEROS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (128, 'SEGUIMIENTO DE PLANES INSTITUCIONALES', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (129, 'SEGUIMIENTO DE PROCESOS CONTENCIOSOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (130, 'SEGUIMIENTO DEL PLAN ANUAL DE CONTRATACIONES', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (131, 'SERVICIOS DE CONTROL POSTERIOR', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (132, 'SERVICIOS DE CONTROL SIMULTANEO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (133, 'SERVICIOS DE VIGILANCIA', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (134, 'SERVICIOS RELACIONADOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (135, 'SESIONES DE CONSEJO DIRECTIVO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (136, 'SESIONES DE CONSEJOS DE USUARIOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (137, 'SESIONES DEL TRIBUNAL DE SOLUCION DE CONTROVERSIAS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (138, 'SOLICITUDES DE ACCESO A LA INFORMACION', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (139, 'SOLICITUDES DE ASIGNACIONES DE VIATICOS', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (140, 'SOLICITUDES DE RECONOCIMIENTO DE INVERSIONES', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (141, 'SUMARIAS ESTADISTICAS AL CONSEJO DE DEFENSA DEL ESTADO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (142, 'SUPERVISIONES DE SERVICIOS DE TECNOLOGIAS DE LA INFORMACIÓN /DE EQUIPOS DE COMPUTO', 'A');
Insert into SERIE
   (IDSERIE, NOMBRE, ESTADO)
 Values
   (143, 'VALORIZACIONES/PLANES DE MANTENIMIENTO CORRECTIVO PREVENTIVO (ORREGIR CREO)', 'A');
