--select * from TIPOIDENTIFICACION;
--DELETE FROM TIPOIDENTIFICACION;
--COMMIT;

Insert into TIPOIDENTIFICACION
   (IDTIPOIDENTIFICACION, NOMBRE)
 Values
   (1, 'RUC');
Insert into TIPOIDENTIFICACION
   (IDTIPOIDENTIFICACION, NOMBRE)
 Values
   (2, 'DNI');
Insert into TIPOIDENTIFICACION
   (IDTIPOIDENTIFICACION, NOMBRE)
 Values
   (3, 'Otro');
Insert into TIPOIDENTIFICACION
   (IDTIPOIDENTIFICACION, NOMBRE)
 Values
   (4, 'CE');
Insert into TIPOIDENTIFICACION
   (IDTIPOIDENTIFICACION, NOMBRE)
 Values
   (5, 'SCE');
Insert into TIPOIDENTIFICACION
   (IDTIPOIDENTIFICACION, NOMBRE)
 Values
   (6, 'CIE');
