--select * from TIPOLEGAJO;
--COMMIT;

Insert into TIPOLEGAJO
   (IDTIPO, DESCRIPCION, ESTADO, NUMERACION)
 Values
   (2, 'CONTRATACION', 'A', 'M');
Insert into TIPOLEGAJO
   (IDTIPO, DESCRIPCION, ESTADO, ACRONIMO, NUMERACION)
 Values
   (3, 'CONTRATACION MENORES', 'A', '-PE', 'M');
Insert into TIPOLEGAJO
   (IDTIPO, DESCRIPCION, ESTADO, ACRONIMO, SECUENCIA, 
    NUMERACION)
 Values
   (1, 'PAGOS', 'A', 'PAG', 'PAGOS_SEQ', 
    'A');
Insert into TIPOLEGAJO
   (IDTIPO, DESCRIPCION, ESTADO, ACRONIMO, SECUENCIA, 
    NUMERACION)
 Values
   (9, 'INTERPRETACION DE CONTRATOS RED VIAL', 'A', 'IRV', 'INTC_SEQ', 
    'A');
Insert into TIPOLEGAJO
   (IDTIPO, DESCRIPCION, ESTADO, ACRONIMO, SECUENCIA, 
    NUMERACION)
 Values
   (10, 'FISCALIZACION DE CONTRATACIONES', 'A', 'LFI', 'FISCA_CONTRA_SEQ', 
    'A');
Insert into TIPOLEGAJO
   (IDTIPO, DESCRIPCION, ESTADO, ACRONIMO, SECUENCIA, 
    NUMERACION)
 Values
   (15, 'DISPOSICION DE BIENES', 'A', '-DB', 'DISPOSICION_BIENES_SEQ', 
    'A');
Insert into TIPOLEGAJO
   (IDTIPO, DESCRIPCION, ESTADO, ACRONIMO, SECUENCIA, 
    NUMERACION)
 Values
   (16, 'ACEPTACION DE DONACION', 'A', '-AD', 'ACEPTACION_DONACION_SEQ', 
    'A');
Insert into TIPOLEGAJO
   (IDTIPO, DESCRIPCION, ESTADO, ACRONIMO, SECUENCIA, 
    NUMERACION)
 Values
   (11, 'SOLICITUDES CONTRACTUALES', 'A', '-SOC', 'SOLIC_CONTRA_SEQ', 
    'A');
Insert into TIPOLEGAJO
   (IDTIPO, DESCRIPCION, ESTADO, ACRONIMO, SECUENCIA, 
    NUMERACION)
 Values
   (12, 'GARANTIAS', 'A', '-GAR', 'GARANTIAS_SEQ', 
    'A');
Insert into TIPOLEGAJO
   (IDTIPO, DESCRIPCION, ESTADO, ACRONIMO, NUMERACION)
 Values
   (13, 'CONTRATOS', 'A', '-CON', 'M');
Insert into TIPOLEGAJO
   (IDTIPO, DESCRIPCION, ESTADO, ACRONIMO, NUMERACION)
 Values
   (14, 'CONTRATOS COMPLEMENTARIOS', 'A', '-CCC', 'M');
