--select * from TIPOLEGAJOUNIDAD;
--commit;

Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (9, 3, 2, 'A', 'C');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (6, 2, 2, 'A', 'A');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (7, 2, 2, 'A', 'C');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (8, 3, 2, 'A', 'A');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (1, 1, 2, 'A', 'C');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (2, 1, 2, 'A', 'A');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (3, 1, 3, 'A', 'A');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (4, 1, 4, 'A', 'A');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (20, 9, 1, 'A', 'C');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (21, 9, 1, 'A', 'A');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (48, 10, 2, 'A', 'C');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (49, 10, 2, 'A', 'A');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (25, 9, 1, 'A', 'C');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (26, 9, 1, 'A', 'A');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (68, 15, 2, 'A', 'C');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (69, 15, 2, 'A', 'A');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (70, 16, 2, 'A', 'C');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (71, 16, 2, 'A', 'A');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (5, 1, 1, 'A', 'A');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (60, 11, 2, 'A', 'A');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (61, 11, 2, 'A', 'C');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (62, 12, 2, 'A', 'A');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (63, 12, 2, 'A', 'C');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (64, 13, 2, 'A', 'A');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (65, 13, 2, 'A', 'C');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (66, 14, 2, 'A', 'A');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (67, 14, 2, 'A', 'C');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (100, 1, 1, 'A', 'V');
Insert into TIPOLEGAJOUNIDAD
   (IDTIPOLEGAJOUNIDAD, IDTIPO, IDUNIDAD, ESTADO, ACCION)
 Values
   (101, 1, 1, 'A', 'V');
