--select * from GRIDCOLUMNAXPERFIL;
--commit;

Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(5, 6);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 7);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 8);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 9);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 10);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 12);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 13);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 14);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 15);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 16);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 38);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 39);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 40);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 41);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 43);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 56);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 57);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 58);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 69);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 70);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 71);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 72);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 73);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 74);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 82);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 90)
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 91);

Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 100);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 101);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 102);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 103);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 104);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 108);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 110);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 120);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 121);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 122);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 123);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 124);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 125);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 126);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 151);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 161);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 163);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 165);
Insert into GRIDCOLUMNAXPERFIL(IDPERFIL, IDGRIDCOLUMNA)Values(6, 197);


