--select * from NUMERACION;
--delete from NUMERACION;
--commit;

Insert into NUMERACION
   (IDUNIDAD, IDTIPODOCUMENTO, NUMEROACTUAL, FORMATO, TIPONUMERACION, 
    FIRMANTE, DESTINATARIO, USUARIOMODIFICACION, 
    FECHAMODIFICACION, ANIOFISCAL)
 Values
   (2, 15, 6, 'N° $NUMERO-2021-CECURV-OSITRAN', 'A', 
    'S', 'I', 2, TO_TIMESTAMP('12/11/2018 16:05:30.098000','fmDDfm/MM/YYYY HH24:MI:SS.FF'), 1);

Insert into NUMERACION
   (IDUNIDAD, IDTIPODOCUMENTO, NUMEROACTUAL, FORMATO, TIPONUMERACION, 
    FIRMANTE, DESTINATARIO, USUARIOMODIFICACION, 
    FECHAMODIFICACION, ANIOFISCAL)
 Values
   (2, 13, 1, 'N° $NUMERO-2021-CECURV-OSITRAN', 'A', 
    'S', 'I', 2, TO_TIMESTAMP('12/11/2018 16:05:30.098000','fmDDfm/MM/YYYY HH24:MI:SS.FF'), 1);

Insert into NUMERACION
   (IDUNIDAD, IDTIPODOCUMENTO, NUMEROACTUAL, FORMATO, TIPONUMERACION, 
    FIRMANTE, DESTINATARIO, USUARIOMODIFICACION, 
    FECHAMODIFICACION, ANIOFISCAL)
 Values
   (2, 17, 1, 'N° $NUMERO-2021-CECURV-OSITRAN', 'A', 
    'S', 'I', 2, TO_TIMESTAMP('12/11/2018 16:05:30.098000','fmDDfm/MM/YYYY HH24:MI:SS.FF'), 1);
