--SET IDENTITY_INSERT TIPODOCUMENTO ON;
--select * from TIPODOCUMENTO;

-- DELETE FROM TIPODOCUMENTO;

Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   (469, 'CARTA DE INSTRUCCIONES DE PAGO', 'CARTA DE INSTRUCCIONES DE PAGO', 'A', 'CARTA_DE_INSTRUCCIONES_DE_PAGO', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (2, 'ACTA', 'ACTA', 'A', 'ACTA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (17, 'RESOLUCION', 'RESOLUCION', 'A', 'RESOLUCION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (18, 'INVITACION', 'INVITACION', 'I', 'INVITACION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (477, 'RENDICION Y-O REEMBOLSO DE GASTOS POR COMISION', 'RENDICION DE GASTOS - REEMBOLSO DE GASTOS POR COMISION DE SERVICIO', 'A', 'RENDICION_DE_GASTOS_REEMBOLSO_DE_GASTOS_COMISION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (20, 'SOBRE CERRADO', 'SOBRE CERRADO', 'I', 'SOBRE_CERRADO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (21, 'ESTADOS CTAS', 'ESTADOS CTAS', 'I', 'ESTADOS_CTAS', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (478, 'ASIGNACION EN USO DE BIENES', 'ASIGNACION EN USO DE BIENES', 'A', 'ASIGNACION_EN_USO_DE_BIENES', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (24, 'C.VITAE', 'C.VITAE', 'A', 'C.VITAE', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (25, 'MEMORIAL', 'MEMORIAL', 'I', 'MEMORIAL', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (479, 'DESPLAZAMIENTO DE BIENES MUEBLES', 'DESPLAZAMIENTO DE BIENES MUEBLES', 'A', 'DESPLA_INT_EXT_BIENES_MUEBLES', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (28, 'RECIBO', 'RECIBO', 'A', 'RECIBO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (480, 'INGRESO-SALIDA DE BIENES DE PROPIEDAD PARTICULAR', 'INGRESO-SALIDA DE BIENES DE PROPIEDAD PARTICULAR', 'A', 'INGRESO_SALIDA_DE_BIENES_DE_PROPIEDAD_PARTICULAR', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (481, 'PEDIDO COMPROBANTE DE SALIDA - PECOSA', 'PEDIDO COMPROBANTE DE SALIDA - PECOSA', 'A', 'PEDIDO_COMPROBANTE_DE_SALIDA_PECOSA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (482, 'DESCANSO FISICO ANUAL POR VACACIONES', 'DESCANSO FISICO ANUAL POR VACACIONES', 'A', 'DESCANSO_FISICO_ANUAL_POR_VACACIONES', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (36, 'DECLARACION JURADA', 'DECLARACION JURADA', 'I', 'DECLARACION_JURADA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (489, 'RESOLUCION TRIBUNAL DE SOLUCION DE CONTROVERSIAS', 'RESOLUCION TRIBUNAL DE SOLUCION DE CONTROVERSIAS', 'A', 'RESOLUCIONES_TRIBUNAL_SOLUCION_CONTROVERSIA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (41, 'ESQUELA', 'ESQUELA', 'I', 'ESQUELA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (493, 'REPORTE ANUAL DE SUPERVISION', 'REPORTE ANUAL DE SUPERVISION', 'A', 'REPORTE_ANUAL_DE_SUPERVISION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (44, 'NOTA DE CARGO', 'NOTA DE CARGO', 'I', 'NOTA_DE_CARGO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (504, 'CERTIFICADO DE PRACTICAS', 'CERTIFICADO DE PRACTICAS', 'A', 'CERTIFICADO_PRACTICAS', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (516, 'ACTA DE APERTURA DEL LIBRO DE FEDATARIOS', 'ACTA DE APERTURA DEL LIBRO DE FEDATARIOS', 'A', 'ACTA_APERTURA_LIBRO_FEDATARIOS', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (92, 'NOTIFICACION', 'NOTIFICACION', 'A', 'NOTIFICACION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (517, 'CONFORMIDAD DE SERVICIO DE FEDATARIOS', 'CONFORMIDAD DE SERVICIO DE FEDATARIOS', 'A', 'CONFORMIDAD_SERVICIO_FEDATARIO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (518, 'ACTA DE ENTREGA DE MATERIALES AL FEDATARIO', 'ACTA DE ENTREGA DE MATERIALES AL FEDATARIO', 'A', 'ACTA_ENTREGA_MATERIALES_FEDATARIO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (519, 'ACUERDO TELETRABAJO CAP', 'ACUERDO DE CAMBIO DE MODALIDAD DE TRABAJO CONVENCIONAL A TELETRABAJO COMPLETO O MIXTO SERVIDOR CAP', 'A', 'ACUERDO_TELETRABAJO_CAP', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (520, 'ADENDA TELETRABAJO CAS', 'ADENDA AL CAS - CAMBIO DE MODALIDAD DE TRABAJO CONVENCIONAL A TELETRABAJO MIXTO O COMPLETO', 'A', 'ADENDA_TELETRABAJO_CAP', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (233, 'CONSTANCIA', 'CONSTANCIA', 'A', 'CONSTANCIA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (43, 'FORMULARIO', 'FORMULARIO', 'I', 'FORMULARIO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (193, 'BOLETIN', 'BOLETIN', 'I', 'BOLETIN', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (29, 'SOLICITUD', 'SOLICITUD', 'I', 'SOLICITUD', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (1, 'MEMORANDO CIRCULAR', 'MEMORANDO CIRCULAR', 'A', 'MEMORANDUM_CIRCULAR', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (324, 'CORREO ELECTRONICO', 'CORREO ELECTRONICO', 'I', 'CORREO_ELECTRONICO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (325, 'NOTA', 'NOTA', 'I', 'NOTA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (31, 'VARIOS', 'VARIOS', 'I', 'VARIOS', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (309, 'CERTIFICADO', 'CERTIFICADO', 'I', 'CERTIFICADO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (247, 'REG. PRESUPUESTAL', 'REG. PRESUPUESTAL', 'I', 'REG._PRESUPUESTAL', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (303, 'AVISO', 'AVISO', 'I', 'AVISO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (306, 'CITACION', 'CITACION', 'I', 'CITACION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (307, 'ACTA DE CONFORMIDAD', 'ACTA DE CONFORMIDAD', 'A', 'ACTA_DE_CONFORMIDAD', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (308, 'ESCRITO', 'ESCRITO', 'A', 'ESCRITO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (61, 'XXX-MEMOS', 'XXX-MEMOS', 'I', 'XXX-MEMOS', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (74, 'CARTA OFICIO', 'CARTA OFICIO', 'I', 'CARTA_OFICIO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (80, 'NOTA TECNICA', 'NOTA TECNICA', 'I', 'NOTA_TECNICA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (321, 'ACTA DE REUNION LABORAL', 'ACTA DE REUNION LABORAL', 'I', 'ACTA_DE_REUNION_LABORAL', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, PIDE)
 Values
   (3, 'CARTA MP', 'CARTA MP', 'A', 'CARTA', 
    'A', '02');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (4, 'CIRCULAR', 'CIRCULAR', 'I', 'CIRCULAR', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (7, 'COTIZACION-PROFORMA', 'COTIZACION-PROFORMA', 'I', 'COTIZACION-PROFORMA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (8, 'DIRECTIVA', 'DIRECTIVA', 'A', 'DIRECTIVA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (10, 'FOLLETO', 'FOLLETO', 'I', 'FOLLETO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (11, 'FACTURA', 'FACTURA', 'A', 'FACTURA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (12, 'INFORME', 'INFORME', 'A', 'INFORME', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (13, 'MEMORANDO', 'MEMORANDO', 'A', 'MEMORANDUM', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR, PIDE, ESTADOPIDE)
 Values
   (15, 'OFICIO', 'OFICIO', 'A', 'OFICIO', 
    'A', '1', '1', '01', 'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR, PIDE, ESTADOPIDE)
 Values
   (327, 'OFICIO CIRCULAR', 'OFICIO CIRCULAR', 'A', 'OFICIO_CIRCULAR', 
    'A', '1', '1', '01', 'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   (328, 'CARTA CIRCULAR', 'CARTA CIRCULAR', 'I', 'CARTA_CIRCULAR', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (333, 'ESTUDIO DE MERCADO', 'ESTUDIO DE MERCADO', 'I', 'ESTUDIO_DE_MERCADO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (334, 'CD-ROM', 'CD-ROM', 'I', 'CD-ROM', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (339, 'COMPROBANTE DE PAGO', 'COMPROBANTE DE PAGO', 'A', 'COMPROBANTE_DE_PAGO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (341, 'OFICIO MULTIPLE MP', 'OFICIO MULTIPLE MP', 'A', 'OFICIO_MULTIPLE', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   (343, 'CONSTANCIA DE PRESTACION', 'CONSTANCIA DE PRESTACION', 'A', 'CONSTANCIA_DE_PRESTACION', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   (345, 'CARTA NOTARIAL', 'CARTA NOTARIAL', 'A', 'CARTA_NOTARIAL', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (351, 'RESOLUCION DIRECTORAL', 'RESOLUCION DIRECTORAL', 'A', 'RESOLUCION_DIRECTORAL', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (355, 'COMUNICADO', 'COMUNICADO', 'I', 'COMUNICADO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (357, 'CARTA MULTIPLE', 'CARTA MULTIPLE', 'A', 'CARTA_MULTIPLE', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (362, 'AFICHE', 'AFICHE', 'I', 'AFICHE', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (376, 'SOLICITUD INF. PUBLICA', 'SOLICITUD INF. PUBLICA', 'A', 'SOLICITUD_INF._PUBLICA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (425, 'TUPA04-PROCEDIMIENTO DE FIJACIÓN Y RE', 'TUPA04-PROCEDIMIENTO DE FIJACION Y RE', 'A', 'TUPA04-PROCEDIMIENTO_DE_FIJACIÓN_Y_RE', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (426, 'TUPA05-PROCEDIMIENTO DE FIJACIÓN TARI', 'TUPA05-PROCEDIMIENTO DE FIJACION TARI', 'A', 'TUPA05-PROCEDIMIENTO_DE_FIJACION_TARI', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (427, 'TUPA06-PROCEDIMIENTO DE DESREGULARIZA', 'TUPA06-PROCEDIMIENTO DE DESREGULARIZA', 'A', 'TUPA06-PROCEDIMIENTO_DE_DESREGULARIZA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (428, 'TUPA07-PROCEDIMIENTO DE EMISOSN DE MA', 'TUPA07-PROCEDIMIENTO DE EMISOSN DE MA', 'A', 'TUPA07-PROCEDIMIENTO_DE_EMISOSN_DE_MA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (429, 'TUPA08-PROCEDIMIENTO DE CUESTIONAMIEN', 'TUPA08-PROCEDIMIENTO DE CUESTIONAMIEN', 'A', 'TUPA08-PROCEDIMIENTO_DE_CUESTIONAMIEN', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (430, 'TUPA09-PROCEDIMIENTO DE IMPUGNACIÓN D', 'TUPA09-PROCEDIMIENTO DE IMPUGNACION D', 'A', 'TUPA09-PROCEDIMIENTO_DE_IMPUGNACION_D', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (431, 'TUPA10-PROCEDIMIENTO DE IMPUGNACION D', 'TUPA10-PROCEDIMIENTO DE IMPUGNACION D', 'A', 'TUPA10-PROCEDIMIENTO_DE_IMPUGNACION_D', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (434, 'TUPA12-PROCEDIMIENTO DE QUEJA CONTRA LOS DEFECTOS ', 'TUPA12-PROCEDIMIENTO DE QUEJA CONTRA LOS DEFECTOS ', 'A', 'TUPA12-PROCEDIMIENTO_DE_QUEJA_CONTRA_LOS_DEFECTOS_', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (435, 'TUPA13-PROCEDMIENTO DE SOLUCION DE CONTROVERSIAS E', 'TUPA13-PROCEDMIENTO DE SOLUCION DE CONTROVERSIAS E', 'A', 'TUPA13-PROCEDMIENTO_DE_SOLUCIÓN_DE_CONTROVERSIAS_E', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (432, 'TUPA14-PROCEDIMIENTO DE IMPUGNACION DE LA DECISION', 'TUPA14-PROCEDIMIENTO DE IMPUGNACION DE LA DECISION', 'A', 'TUPA14-PROCEDIMIENTO_DE_IMPUGNACIÓN_DE_LA_DECISIÓN', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (433, 'TUPA15-PROCEDIMIENTO DE IMPUGNACIÓN DE LA DENEGATO', 'TUPA15-PROCEDIMIENTO DE IMPUGNACIÓN DE LA DENEGATO', 'A', 'TUPA15-PROCEDIMIENTO_DE_IMPUGNACIÓN_DE_LA_DENEGATO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (14, 'HOJA LIQUIDACION PAGO', 'HOJA LIQUIDACION PAGO', 'I', 'HOJA_LIQUIDACION_PAGO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (418, 'CONSULTA PUB.-PORTAL USU.', 'CONSULTA PUB.-PORTAL USU.', 'I', 'CONSULTA_PUB.-PORTAL_USU.', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (420, 'SUGERENCIA-PORTAL USU.', 'SUGERENCIA-PORTAL USU.', 'I', 'SUGERENCIA-PORTAL_USU.', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (421, 'DENUNCIA PUB.-PORTAL USU.', 'DENUNCIA PUB.-PORTAL USU.', 'I', 'DENUNCIA_PUB.-PORTAL_USU.', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (46, 'INF. TEC. EV. SOFT.', 'INF. TEC. EV. SOFT.', 'I', 'INFTECEVSOFT', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (436, 'NOTA DE CREDITO', 'NOTA DE CREDITO', 'A', 'NOTA_CREDITO_ELECTRONICA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (438, 'INFORME TECNICO', 'INFORME TECNICO', 'I', 'INFORME_TECNICO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (440, 'NOTA DE DEVENGADO', 'NOTA DE DEVENGADO', 'A', 'NOTA_DE_DEVENGADO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (441, 'NOTA DE DEVOLUCION', 'NOTA DE DEVOLUCION', 'A', 'NOTA_DE_DEVOLUCION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (439, 'CONTROL DE PAGOS', 'CONTROL DE PAGOS ', 'A', 'CONTROL_DE_PAGOS', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (442, 'MEMORANDO CONJUNTO', 'MEMORANDO CONJUNTO', 'A', 'MEMORANDO_CONJUNTO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (443, 'ACTA DE SESION DE CONSEJO DIRECTIVO', 'ACTA DE SESION DE CONSEJO DIRECTIVO', 'A', 'ACTA_DE_SESION_DE_CONSEJO_DIRECTIVO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (444, 'ACTA DE CUERPO COLEGIADO', 'ACTA DE CUERPO COLEGIADO', 'A', 'ACTA_DE_CUERPO_COLEGIADO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (445, 'AGENDA DE SESION', 'AGENDA DE SESION', 'A', 'AGENDA_DE_SESION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (384, 'FEDEX', 'FEDEX', 'I', 'FEDEX', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (386, 'CARTA FIANZA', 'CARTA FIANZA', 'I', 'CARTA_FIANZA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (395, 'NOTA CIRCULAR', 'NOTA CIRCULAR', 'I', 'NOTA_CIRCULAR', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (396, 'INFORME CONJUNTO', 'INFORME CONJUNTO', 'A', 'INFORME_CONJUNTO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (399, 'PAPELETA DE INFRACCION', 'PAPELETA DE INFRACCION', 'I', 'PAPELETA_DE_INFRACCION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (397, 'NOTA DE OPERACION', 'NOTA DE OPERACION', 'I', 'NOTA_DE_OPERACION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (400, 'FACTURA ELECTRONICA', 'FACTURA ELECTRONICA', 'A', 'FACTURA_ELECTRONICA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, SICOR)
 Values
   (402, 'AGENDAS DE INSPECCION', 'AGENDAS DE INSPECCION', 'A', 'AGENDAS_DE_INSPECCION', 
    'A', '1');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (403, 'ACTAS DE INSPECCION', 'ACTAS DE INSPECCION', 'A', 'ACTAS_DE_INSPECCION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, SICOR)
 Values
   (404, 'ACTA DE REUNION DE TRAB.', 'ACTA DE REUNION DE TRAB.', 'A', 'ACTA_DE_REUNION_DE_TRAB', 
    'A', '1');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, SICOR)
 Values
   (405, 'AGENDA DE REUNION DE TRAB.', 'AGENDA DE REUNION DE TRAB.', 'A', 'AGENDA_DE_REUNION_DE_TRAB', 
    'A', '1');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (408, 'MANDATOS DE ACCESO', 'MANDATOS DE ACCESO', 'I', 'MANDATOS_DE_ACCESO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (409, 'PROVEIDO', 'PROVEIDO', 'I', 'PROVEIDO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (414, 'HOJA DE RECLAMACION', 'HOJA DE RECLAMACION', 'A', 'HOJA_DE_RECLAMACION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (415, 'INDAGACIÓN DE MERCADO', 'INDAGACIÓN DE MERCADO', 'I', 'INDAGACIÓN_DE_MERCADO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (437, 'CARGO DE ENTREGA', 'CARGO DE ENTREGA', 'I', 'CARGO_DE_ENTREGA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (422, 'TUPA01-PROCEDIMIENTO PARA LA CALIFICA', 'TUPA01-PROCEDIMIENTO PARA LA CALIFICA', 'A', 'TUPA01-PROCEDIMIENTO_PARA_LA_CALIFICA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (423, 'TUPA02-SOLICITUD DE ACCESO A LA INFOR', 'TUPA02-SOLICITUD DE ACCESO A LA INFOR', 'A', 'TUPA02-SOLICITUD_DE_ACCESO_A_LA_INFOR', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (424, 'TUPA03-PROCEDIMIENTO PARA LA INTERPRE', 'TUPA03-PROCEDIMIENTO PARA LA INTERPRE', 'A', 'TUPA03-PROCEDIMIENTO_PARA_LA_INTERPRE', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (467, 'CARTA ORDEN', 'CARTA ORDEN', 'A', 'CARTA_ORDEN', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (468, 'CARTA ORDEN ELECTRONICA', 'CARTA ORDEN ELECTRONICA', 'A', 'CARTA_ORDEN_ELECTRONICA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (470, 'REPORTE', 'REPORTE', 'A', 'REPORTE', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   (471, 'RESOLUCION DE DETERMINACION', 'RESOLUCION DE DETERMINACION', 'A', 'RESOLUCION_DETERMINACION', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (472, 'ORDEN DE PAGO', 'ORDEN DE PAGO', 'A', 'ORDEN_PAGO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (473, 'APROBACION DE EXPEDIENTE DE CONTRATACION', 'APROBACION DE EXPEDIENTE DE CONTRATACION', 'A', 'APROBACION_EXPEDIENTE_CONTRATACION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (474, 'DESIGNACION DE COMITE DE SELECCION', 'DESIGNACION DE COMITE DE SELECCION', 'A', 'DESIGNACION_COMITE_SELECCION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (475, 'APROBACION DE DOCUMENTOS DEL PROCEDIMIENTO DE SELECCION', 'APROBACION DE DOCUMENTOS DEL PROCEDIMIENTO DE SELECCION', 'A', 'APROBACION_DOCUMENTOS_PROCEDIMIENTO_SELECCION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (495, 'LISTA DE PARTICIPANTES EN LAS REUNIONES DE OSITRAN', 'LISTA DE PARTICIPANTES EN LAS REUNIONES DE OSITRAN', 'I', 'LISTA_PARTICIPANTES_REUNIONES_OSITRAN', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (496, 'SOLICITUD DE INSCRIPCION', 'SOLICITUD DE INSCRIPCION', 'A', 'SOLICITUD_INSCRIPCION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (497, 'CONSTANCIA DE ASISTENCIA A INFORME ORAL', 'CONSTANCIA DE ASISTENCIA A INFORME ORAL', 'A', 'CONSTANCIA_ASISTENCIA_INFORME_ORAL', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (505, 'ACTA DE INSPECCION INOPINADA', 'ACTA DE INSPECCION INOPINADA', 'A', 'ACTA_INSPECCION_INOPINADA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (506, 'AGENDA DE INSPECCION INOPINADA', 'AGENDA DE INSPECCION INOPINADA', 'A', 'AGENDA_INSPECCION_INOPINADA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (507, 'CONSTANCIA DE DEVOLUCION DE MATERIALES FEDATARIOS', 'CONSTANCIA DE DEVOLUCION DE MATERIALES FEDATARIOS', 'A', 'CONSTANCIA_DEV_MAT_FEDATARIOS', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (508, 'INVENTARIO DE BIENES MUEBLES', 'INVENTARIO DE BIENES MUEBLES', 'A', 'INVENTARIO_DE_BIENES_MUEBLES', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (514, 'ACTA DE DESARCHIVAMIENTO', 'ACTA DE DESARCHIVAMIENTO', 'A', 'ACTA_DESARCHIVAMIENTO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (446, 'FORMULARIO DE CREACION DE SIGLAS EN EL SGD', 'FORMULARIO DE CREACION DE SIGLAS EN EL SGD', 'A', 'FORM_SIGLAS', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (447, 'FORMULARIO DE CREACION DE NUEVOS TIPOS DOC', 'FORMULARIO DE CREACION DE NUEVOS TIPOS DOC', 'A', 'FORM_TIPOS', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (451, 'HABILITACION Y CERTIFICACION PRESUPUESTAL', 'HABILITACION Y CERTIFICACION PRESUPUESTAL', 'A', 'HABILITACION_CERTIFICACION_PRESUPUESTAL', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (452, 'ESTADO DE CUENTA', 'ESTADO DE CUENTA', 'A', 'ESTADO_DE_CUENTA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   (453, 'RESOLUCION DE MULTA', 'RESOLUCION DE MULTA', 'A', 'RESOLUCION_DE_MULTA', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (454, 'PEDIDO DE SERVICIO', 'PEDIDO DE SERVICIO', 'A', 'PEDIDO_DE_SERVICIO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (455, 'PEDIDO DE COMPRA', 'PEDIDO DE COMPRA', 'A', 'PEDIDO_DE_COMPRA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   (456, 'ORDEN DE SERVICIO', 'ORDEN DE SERVICIO', 'A', 'ORDEN_DE_SERVICIO', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   (457, 'ORDEN DE COMPRA', 'ORDEN DE COMPRA', 'A', 'ORDEN_DE_COMPRA', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (460, 'CEDULA DE COMUNICACION', 'CEDULA DE COMUNICACION', 'A', 'CEDULA_DE_COMUNICACION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (461, 'REPORTE DE INFORMACION', 'REPORTE DE INFORMACION', 'A', 'REPORTE_DE_INFORMACION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (465, 'RENDICION DE FONDOS DE CAJA CHICA', 'RENDICION DE FONDOS DE CAJA CHICA', 'A', 'RENDICION_DE_FONDOS_DE_CAJA_CHICA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (466, 'RECIBO DE INGRESO', 'RECIBO DE INGRESO', 'A', 'RECIBO_DE_INGRESO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (476, 'FORMULARIO DE DENUNCIAS', 'FORMULARIO DE DENUNCIAS', 'A', 'FORMULARIO_DENUNCIAS', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (486, 'REQUERIMIENTO', 'REQUERIMIENTO', 'A', 'REQUERIMIENTO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (487, 'RESULTADO DE REQUERIMIENTO', 'RESULTADO DE REQUERIMIENTO', 'I', 'RESULTADO_REQUERIMIENTO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (490, 'CONTRATO', 'CONTRATO', 'A', 'CONTRATO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (491, 'ADENDA', 'ADENDA', 'A', 'ADENDA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (499, 'PLAN DE VISITA DE CONTROL', 'PLAN DE VISITA DE CONTROL', 'A', 'PLAN_VISITA_CONTROL', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (500, 'PLAN DE CONTROL CONCURRENTE', 'PLAN DE CONTROL CONCURRENTE', 'A', 'PLAN_CONTROL_CONCURRENTE', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (501, 'INFORME DE VISITA DE CONTROL', 'INFORME DE VISITA DE CONTROL', 'A', 'INFORME_VISITA_CONTROL', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (502, 'INFORME DE CONTROL CONCURRENTE', 'INFORME DE CONTROL CONCURRENTE', 'A', 'INFORME_CONTROL_CONCURRENTE', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (503, 'INFORME DE ORIENTACION DE OFICIO', 'INFORME DE ORIENTACION DE OFICIO', 'A', 'INFORME_ORIENTACION_OFICIO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (509, 'CONSTANCIA DE PRESTAMO DE DOCUMENTOS', 'CONSTANCIA DE PRESTAMO DE DOCUMENTOS', 'A', 'CONSTANCIA_PRESTAMO_DOCUMENTOS', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (510, 'CONSTANCIA DE DEVOLUCION DE DOCUMENTOS', 'CONSTANCIA DE DEVOLUCION DE DOCUMENTOS', 'A', 'CONSTANCIA_DEVOLUCION_DOCUMENTOS', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (515, 'DECLARACION JURADA - DDJJ', 'DECLARACION JURADA - DDJJ', 'A', 'DECLARACION_JURADA_DDJJ', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (448, 'NOTA DE CERTIFICADO PRESUPUESTAL', 'NOTA DE CERTIFICADO PRESUPUESTAL', 'A', 'NOTA_DE_CERTIFICADO_PRESUPUESTAL', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (449, 'NOTA DE HABILITACION PRESUPUESTAL', 'NOTA DE HABILITACION PRESUPUESTAL', 'A', 'NOTA_DE_HABILITACION_PRESUPUESTAL', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (450, 'CUADRO COMPARATIVO DE PRECIOS', 'CUADRO COMPARATIVO DE PRECIOS', 'A', 'CUADRO_COMPARATIVO_DE_PRECIOS', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (458, 'HOJA INFORMATIVA', 'HOJA INFORMATIVA', 'A', 'HOJA_INFORMATIVA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (459, 'CEDULA DE COMUNICACION', 'CEDULA DE COMUNICACION', 'A', 'CEDULA_DE_COMUNICACION', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (462, 'NOTA CONTABLE', 'NOTA CONTABLE', 'A', 'NOTA_CONTABLE', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   (463, 'REQUERIMIENTO TRIBUTARIO', 'REQUERIMIENTO TRIBUTARIO', 'A', 'REQUERIMIENTO_TRIBUTARIO', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION, EXTERNO, EXTERNOQR)
 Values
   (464, 'RESULTADO DE REQUERIMIENTO TRIBUTARIO', 'RESULTADO DE REQUERIMIENTO TRIBUTARIO', 'A', 'RESULTADO_REQUERIMIENTO_TRIBUTARIO', 
    'A', '1', '1');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (483, 'CONSTANCIA DE TRABAJO', 'CONSTANCIA DE TRABAJO', 'A', 'CONSTANCIA_DE_TRABAJO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (484, 'CONSTANCIA DE PRACTICAS', 'CONSTANCIA DE PRACTICAS', 'A', 'CONSTANCIA_DE_PRACTICAS', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (485, 'CERTIFICADO DE TRABAJO', 'CERTIFICADO DE TRABAJO', 'A', 'CERTIFICADO_DE_TRABAJO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (492, 'ACTA DE INSPECCION NO PROGRAMADA', 'ACTA DE INSPECCION NO PROGRAMADA', 'A', 'ACTA_INSPECCION_NO_PROGRAMADA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (494, 'NOTA DE CONTABILIDAD - SIAF', 'NOTA DE CONTABILIDAD - SIAF', 'A', 'NOTA_CONTABILIDAD_SIAF', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (498, 'CONVENIO DE ACUMULACION DE VACACIONES', 'CONVENIO DE ACUMULACION DE VACACIONES', 'A', 'CONVENIO_ACUMULACION_VACACIONES', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (511, 'AYUDA DE MEMORIA', 'AYUDA MEMORIA', 'A', 'AYUDA_MEMORIA', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (512, 'REPORTE DE TRABAJO REMOTO', 'REPORTE DE TRABAJO REMOTO', 'A', 'REPORTE_DE_TRABAJO_REMOTO', 
    'A');
Insert into TIPODOCUMENTO
   (IDTIPODOCUMENTO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, 
    TIPONUMERACION)
 Values
   (513, 'PLAN', 'PLAN', 'A', 'PLAN', 
    'A');
