--select * from TIPOINSTITUCION;

--DELETE FROM TIPOINSTITUCION;

Insert into TIPOINSTITUCION
   (COD_TIPOINSTITUCION, DES_TIPOINSTITUCION, FLA_ACTIVO)
 Values
   (1, 'Entidades', '1');
Insert into TIPOINSTITUCION
   (COD_TIPOINSTITUCION, DES_TIPOINSTITUCION, FLA_ACTIVO)
 Values
   (2, 'Empresas', '1');
Insert into TIPOINSTITUCION
   (COD_TIPOINSTITUCION, DES_TIPOINSTITUCION, FLA_ACTIVO)
 Values
   (3, 'Persona Natural', '1');
