--SET IDENTITY_INSERT GRIDXGRIDCOLUMNA ON;
--select * from GRIDXGRIDCOLUMNA;

Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (26, 32, 3008);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (26, 42, 2041);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (26, 1, 2044);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (26, 6, 2047);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (26, 4, 2065);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (26, 14, 2068);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (26, 10, 2083);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (26, 35, 2098);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (26, 12, 3001);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (26, 48, 2025);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (26, 20, 2024);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (26, 8, 2022);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (26, 34, 2072);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (26, 3, 2073);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (26, 5, 2071);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 49, 954);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (26, 18, 3010);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (5, 21, 959650);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 1, 100);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 2, 90);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 3, 126);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 4, 120);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 5, 122);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 6, 110);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (24, 6, 208);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 10, 151);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (3, 14, 321);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 12, 165);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (2, 1, 200);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (2, 3, 223488);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (2, 4, 220);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (2, 6, 210);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (2, 5, 950510);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (24, 4, 247);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (2, 14, 221);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (3, 1, 300);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (3, 4, 320);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (3, 12, 388980);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (3, 6, 310);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (3, 45, 777);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (4, 16, 180800);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (4, 17, 759200);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (4, 18, 39728);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (4, 15, 379480);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (4, 5, 349940);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (4, 1, 145828);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (5, 1, 372590);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (5, 4, 146400);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (5, 5, 521425);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (6, 1, 643562);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (24, 14, 251);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (6, 12, 822536);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (6, 5, 585500);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (7, 1, 700);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (18, 44, 182222);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (7, 10, 43333);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (9, 14, 1000);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (7, 12, 101808);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (8, 1, 800);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (8, 3, 281712);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (8, 4, 820);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (8, 5, 993640);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (8, 6, 810);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (8, 10, 879280);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (24, 5, 256);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (8, 12, 238784);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (5, 20, 728100);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (7, 4, 720);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (24, 42, 204);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (14, 1, 1400);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (14, 3, 510727);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (14, 4, 1420);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (14, 5, 135499);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (14, 6, 1410);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (14, 10, 136723);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (14, 12, 142896);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (16, 10, 9032830);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (17, 10, 9032832);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (7, 14, 721);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (16, 5, 140314);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (16, 1, 231209);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (16, 18, 362551);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (16, 15, 419758);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (16, 16, 121730);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (17, 5, 479397);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (17, 18, 320566);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (17, 15, 491943);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (17, 16, 454327);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (17, 14, 590145);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (3, 10, 998);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (24, 10, 257);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 14, 121);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (9, 1, 900);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (9, 4, 920);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (9, 5, 476525);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (9, 20, 905);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (9, 6, 910);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (24, 12, 289);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (9, 10, 965700);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (9, 12, 4456680);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (17, 30, 9032835);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (16, 31, 9032836);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (17, 31, 9032837);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (16, 30, 9032834);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (9, 32, 901);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 20, 101);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (18, 4, 1810);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (24, 1, 205);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (18, 6, 1800);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (18, 10, 9032843);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (18, 12, 9032845);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (4, 31, 9032850);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 34, 125);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (7, 6, 713);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 35, 161);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (7, 35, 44455);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (19, 1, 6);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (19, 4, 7);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (19, 5, 8);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (19, 6, 9);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (19, 10, 10);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (19, 12, 12);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (19, 14, 13);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (19, 18, 14);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (19, 34, 15);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (19, 35, 16);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (19, 38, 19);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (20, 35, 26);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (20, 6, 20);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (20, 34, 22);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (20, 5, 23);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (20, 10, 25);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (20, 4, 21);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (23, 1, 70);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (20, 12, 27);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (20, 18, 28);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (20, 1, 30);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (7, 8, 698);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (7, 20, 705);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (22, 1, 39);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (22, 6, 40);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (22, 10, 56);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (22, 12, 58);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (22, 14, 43);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (22, 35, 57);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (23, 35, 69);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (23, 3, 71);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (23, 5, 72);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (23, 10, 73);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (23, 12, 74);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (7, 43, 724);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (3, 35, 999);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (9, 35, 4456679);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (18, 35, 9032844);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (22, 4, 41);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (24, 35, 288);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 42, 104);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (2, 42, 201);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (7, 42, 711);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (3, 42, 290);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (2, 42, 82);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (18, 42, 108);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (5, 42, 415);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (9, 42, 842);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (22, 42, 38);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (25, 4, 2040);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (25, 6, 2039);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (25, 10, 2048);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (25, 12, 2059);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (25, 35, 2058);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (25, 42, 2035);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (25, 46, 2046);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (25, 14, 2045);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 47, 950);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (7, 47, 9999999);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (24, 47, 952);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (24, 2, 197);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 50, 955);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (7, 50, 9999998);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 36, 102);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 56, 123);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 55, 124);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 57, 103);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (3, 76, 305);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (3, 15, 325);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (34, 8, 6080);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (34, 20, 6081);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (34, 48, 6082);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (34, 68, 6083);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (34, 42, 6084);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (34, 1, 6085);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (34, 6, 6086);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (34, 4, 6087);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (34, 14, 6088);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (34, 5, 6089);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (34, 34, 6090);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (34, 3, 6091);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (34, 10, 6092);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (34, 35, 6093);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (34, 12, 6094);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (34, 32, 6095);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (34, 18, 6096);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (35, 8, 7080);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (35, 20, 7081);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (35, 48, 7082);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (35, 68, 7083);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (35, 42, 7084);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (35, 1, 7085);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (35, 6, 7086);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (35, 4, 7087);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (35, 14, 7088);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (35, 5, 7089);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (35, 34, 7090);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (35, 3, 7091);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (35, 10, 7092);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (35, 35, 7093);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (35, 12, 7094);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (35, 32, 7095);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (35, 18, 7096);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (36, 59, 4420);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (36, 61, 4421);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (36, 64, 4422);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (36, 62, 4423);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (36, 6, 4426);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (36, 14, 4427);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (36, 43, 4428);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (36, 12, 4429);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (37, 36, 2603);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (40, 36, 3307);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (33, 79, 5245);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (33, 58, 5255);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (33, 77, 5249);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (24, 25, 246);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (18, 25, 9032840);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (33, 60, 5220);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (33, 64, 5221);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (33, 67, 5222);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (33, 62, 5223);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (33, 4, 5224);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (33, 6, 5225);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (33, 14, 5226);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (33, 43, 5227);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (33, 12, 5230);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (36, 4, 4424);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (33, 5, 5229);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (37, 80, 2609);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (27, 4, 8000);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (28, 4, 9000);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (27, 6, 8001);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (28, 6, 9001);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (27, 14, 8002);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (27, 12, 8005);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (27, 43, 8004);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (28, 59, 8882);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (28, 14, 9002);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (28, 43, 9003);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (28, 12, 9006);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (27, 60, 7994);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (28, 61, 8884);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (27, 62, 7997);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (28, 62, 8886);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (28, 63, 8888);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (27, 64, 7995);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (27, 67, 7996);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (28, 64, 8885);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (32, 8, 5238);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (32, 1, 5240);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (32, 20, 5242);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (32, 42, 5244);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (32, 58, 5246);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (32, 6, 5248);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (32, 4, 5250);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (32, 14, 5252);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (32, 43, 5254);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (32, 10, 5256);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (32, 35, 5258);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (32, 12, 5260);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (32, 50, 5262);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (32, 47, 5264);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (30, 66, 4073);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (31, 66, 5032);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 58, 91);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (7, 58, 712);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (30, 14, 4074);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (31, 52, 5030);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (31, 1, 5028);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (31, 51, 5029);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (31, 53, 5031);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (31, 14, 5036);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (31, 65, 5037);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (31, 43, 5038);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (30, 1, 4069);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (30, 51, 4070);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (30, 52, 4071);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (30, 43, 4078);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (30, 53, 4072);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (30, 65, 4075);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (7, 68, 707);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (26, 68, 2038);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (24, 34, 212);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (3, 69, 302);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (24, 71, 209);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (24, 70, 240);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (38, 59, 7428);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (37, 74, 2608);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (38, 62, 7429);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (38, 4, 7432);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (38, 6, 7434);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (38, 14, 7436);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (38, 43, 7438);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (38, 12, 7440);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (39, 59, 9200);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (39, 62, 9202);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (39, 4, 9209);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (39, 6, 9212);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (39, 34, 9213);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (39, 5, 9215);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (39, 12, 9218);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (39, 72, 9201);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (39, 3, 9214);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (40, 62, 3300);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (40, 73, 3303);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (40, 72, 3306);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (40, 6, 3309);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (40, 4, 3312);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (40, 12, 3315);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (40, 75, 3318);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (40, 74, 3321);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (40, 34, 3324);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (40, 3, 3327);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (40, 5, 3330);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (37, 6, 2604);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (37, 62, 2600);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (37, 4, 2605);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (37, 75, 2607);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (37, 34, 2610);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (37, 3, 2611);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (37, 5, 2612);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (37, 72, 2602);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (37, 73, 2601);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (37, 12, 2606);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (1, 78, 163);
Insert into GRIDXGRIDCOLUMNA
   (IDGRID, IDGRIDCOLUMNA, ID)
 Values
   (3, 78, 1002);
