--SET IDENTITY_INSERT NUMERACION ON;
--select * from NUMERACION;
--delete from NUMERACION;

Insert into NUMERACION
   (IDUNIDAD, IDTIPODOCUMENTO, NUMEROACTUAL, FORMATO, TIPONUMERACION, 
    FIRMANTE, DESTINATARIO, USUARIOMODIFICACION, 
    FECHAMODIFICACION, ANIOFISCAL)
 Values
   (2, 15, 6, 'N° $NUMERO-2021-CECURV-OSITRAN', 'A', 
    'S', 'I', 2, GETDATE(), 1);

Insert into NUMERACION
   (IDUNIDAD, IDTIPODOCUMENTO, NUMEROACTUAL, FORMATO, TIPONUMERACION, 
    FIRMANTE, DESTINATARIO, USUARIOMODIFICACION, 
    FECHAMODIFICACION, ANIOFISCAL)
 Values
   (2, 13, 1, 'N° $NUMERO-2021-CECURV-OSITRAN', 'A', 
    'S', 'I', 2, GETDATE(), 1);

Insert into NUMERACION
   (IDUNIDAD, IDTIPODOCUMENTO, NUMEROACTUAL, FORMATO, TIPONUMERACION, 
    FIRMANTE, DESTINATARIO, USUARIOMODIFICACION, 
    FECHAMODIFICACION, ANIOFISCAL)
 Values
   (2, 17, 1, 'N° $NUMERO-2021-CECURV-OSITRAN', 'A', 
    'S', 'I', 2, GETDATE(), 1);
