--select * from DEPARTAMENTO;
/*
DELETE FROM CLIENTE;
DELETE FROM USUARIO;
DELETE FROM UNIDAD;
DELETE FROM SEDE;
DELETE FROM DISTRITO;
DELETE FROM PROVINCIA;
DELETE FROM DEPARTAMENTO;
*/


Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (10000, 'AMAZONAS');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (20000, 'ANCASH');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (30000, 'APURIMAC');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (40000, 'AREQUIPA');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (50000, 'AYACUCHO');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (60000, 'CAJAMARCA');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (70000, 'CALLAO');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (80000, 'CUSCO');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (90000, 'HUANCAVELICA');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (100000, 'HUANUCO');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (110000, 'ICA');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (120000, 'JUNIN');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (130000, 'LA LIBERTAD');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (140000, 'LAMBAYEQUE');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (150000, 'LIMA');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (160000, 'LORETO');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (170000, 'MADRE DE DIOS');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (180000, 'MOQUEGUA');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (190000, 'PASCO');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (200000, 'PIURA');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (210000, 'PUNO');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (220000, 'SAN MARTIN');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (230000, 'TACNA');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (240000, 'TUMBES');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (250000, 'UCAYALI');
Insert into DEPARTAMENTO
   (IDDEPARTAMENTO, NOMBRE)
 Values
   (980000, 'EXPORTACION');
